### ISSUE TITLE
Default search suggestions not working

### ISSUE THREAD

**Issue by mthanos7** [microsoft-search/pnp-modern-search#120]
It doesn't seem like either the Custom Suggestion Provider or the Sharepoint Query Suggestions (the one calling the built in REST API) are working for me. The 'configure suggestions' button doesn't show up and a suggestion drop down pops up when I type in the search box but nothing is suggested and it disappears after a few seconds. Are these suggestion providers meant to work out of the box or am I meant to modify the extensibility library/CustomSuggestionProvider class?

**Comment by FranckyC** [comment]
Hi @mthanos7, the default suggestion endpoint uses the SharePoint search `suggest` API that returns static set of manual suggestions (see https://docs.microsoft.com/en-us/sharepoint/search/manage-query-suggestions). It returns nothing simply because you haven't defined suggestions yet. For the custom ones, this is just an example to get you started to write your owns. You have to add the extensibility solution to your app catalog (site or global) to have them displayed in the Web Part.

**Comment by wobba** [comment]
To point out, it will return learned  suggestions as well, but how that works is a bit complicated. It's tied to users clicking a search result joined with site Url and result source. And in classic, to record the click.
