### ISSUE TITLE
Problems with Internet Explorer when configuring redirect to another search page

### ISSUE THREAD

**Issue by markferkaluk** [microsoft-search/pnp-modern-search#124]
We are using Internet Explorer 11 and have a problem when using the Search WebPart. Please have a look at the screenshot. The error appears when the page is loading. The Search WebPart is configured to redirect to another search result page.

![Anmerkung 2020-03-04 101622](https://user-images.githubusercontent.com/8750279/75875037-3aac9580-5e13-11ea-94d7-6bc0cc1fe092.png)
![InkedAnmerkung 2020-03-04 101621_LI](https://user-images.githubusercontent.com/8750279/75875040-3b452c00-5e13-11ea-8396-f5f5ca802061.jpg)

**Comment by wobba** [comment]
Which version are you using, and can you share more information about the actual setup, in order to possibly reproduce it.

But from the screenshot it seems to be a method "find" which is missing a polyfill for IE11.

And have to say, that supporting IE11, is probably not a main priority, but we will do our best :)

**Comment by markferkaluk** [comment]
Hey, sorry for the late reply. We are using version 3.9.0.0.
To reproduce: We just configure the Search Box WebPart to send the query to a new page as (in a new tab) as URL fragment.

Then, when just loading the page, the error appears. But not all the time! Sometimes the error doesn't show up and it works.

**Comment by wobba** [comment]
I'm fixing the .find issues in the code.
