### ISSUE TITLE
How can i use custom handlebar expression in filters webpart?

### ISSUE THREAD

**Issue by davemehr** [microsoft-search/pnp-modern-search#1278]
**Version used**
4.3

**Question**
I show the folder name of a document, where they stored, in the Search result webpart with an expression (i help with https://github.com/microsoft-search/pnp-modern-search/issues/989 ;) ). Is it also possible, that i can use expressions in the filter webpart? Or how is it possible, tho bring the folder name to the filters webpart?

**Screenshots**
Search results webpart with expresion:
![search result webpart manage columns with expression](https://user-images.githubusercontent.com/65955023/132649468-40f9bcdd-6300-4ffa-b031-63e25b342137.png)

Search filters webpart without expressions:
![search filters webpart with no expressions](https://user-images.githubusercontent.com/65955023/132649445-377346f8-2f41-4550-a1ab-a2fcf701c6dd.png)

**Additional context**
Thanks for inputs ;)

**Comment by FranckyC** [comment]
Hi @davemehr, you can't use expressions in the Web Part configuration. However, you can still format the output value for a specific filter in the Handlebars template directly, the same way as the Search Results Web Part:

![image](https://user-images.githubusercontent.com/5659122/132892116-27dc797f-e209-4361-aa47-64829196355f.png)

**Comment by davemehr** [comment]
@FranckyC yes, we will try and test it and i come back to this thread.

**Comment by FranckyC** [comment]
As the question is resolved, I'll close this one for now. Feel free to open an other issue if needed related to templating.

**Comment by pastorjustin** [comment]
@FranckyC  or @wobba , using @davemehr 's example, where exactly would one put the code that works on the search results page '{{replace (first (last (split (slot item @root.slots.Path) "/") 2)) "%20" " " }}' into the Filters template.  I am struggling because the template does not allow for formatting by individual filter/refiner.  Would I need to call that out somehow?  Can someone show an example on how this would work.  I can't seem to find any documentation on this part.

Lastly, is there another way?  In my case, I created a RefinableString in O365 that points to the ParentLink.  Is there anyway in the metadata/search side to pre-filter this so that the index data only contains the parent folder?  That is what the client wants, to filter files based on what folder they are in.

You can see in my image below, I have the results working perfectly with the parent folder, but I can't filter without showing the whole URL.

![image](https://user-images.githubusercontent.com/24571058/228917792-0887bb3a-c35a-4426-8a3b-c315623e40ee.png)

![image](https://user-images.githubusercontent.com/24571058/228916146-1c3aca6a-0625-4be8-8d60-cf49d208ee59.png)
