### ISSUE TITLE
Search results showing Error " [HTTP]:500 - [CorrelationId]:bcaaee9f-90a5-3000-1326-9e53f1bb033e [Version]:16.0.0.21625 -" for specific keyword  

### ISSUE THREAD

**Issue by PratapAjaySolanki** [microsoft-search/pnp-modern-search#1279]
Hi, 

I am using "PnP Modern Search - Search Web Parts - v4" (Version- 4.3) in our SharePoint online search page. I am encountering an issue while searching the content only for a specific keyword. 
Below is the detailed description of the issue
Case :1 
When I am searching for keyword "Subsea Tree" it is returning results (around 18 results) as mentioned in the below screenshot

![image](https://user-images.githubusercontent.com/90385207/132662409-8d201cc9-c966-406c-8578-a90f1489a582.png)

Case 2: When I am searching for keyword "Subsea Trees" it is giving below error in search results

![image](https://user-images.githubusercontent.com/90385207/132662952-50e0a2f8-36f4-4f94-817d-e6753e336b04.png)

Case 3: When I am searching for the keyword within the quotes it is returning the results

![image](https://user-images.githubusercontent.com/90385207/132663948-cf2ec8cd-9c79-41b6-b202-fc8ef6134d45.png)

 
Issue Description: As explained, the only difference in between the two search keywords is of only a single character i.e. "s"
It is returning results for any other keywords which we are using for filtering the results but only in case of Subsea Trees it is throwing error as mentioned above.

Please guide me what exactly I am missing or any fix for this issue.

**Comment by FranckyC** [comment]
Hi @PratapAjaySolanki, when the error occurs, can you go in the 'Network' tab of the browser and inspect the call? You should see a more explicit error message in the response. Difficult to say what could cause this otherwise.

Also, you mention a 403 error in the issue title, but I only see a HTTP 500 error in the screenshot. If it is a 403, it usually means permissions issues are often not related to the Web Part itself but hte content you are trying to view.

**Comment by PratapAjaySolanki** [comment]
Hi @FranckyC 

Thanks for your response
Only once I got this 403 error, otherwise every time it is throwing HTTP 500 error.
As you suggested below is the network header and its response. In response also it just saying "An unknown error occurred".


**Header(General) :** 
Request URL: /_api/search/postquery
Request Method: POST
Status Code: 500 
Remote Address: 13.123.118.9:443
Referrer Policy: strict-origin-when-cross-origin

**Response**:
{"odata.error":{"code":"-1, Microsoft.Office.Server.Search.REST.SearchServiceException","message":{"lang":"en-US","value":"An unknown error occurred."}}}

**Comment by wobba** [comment]
Could be releated to #1262 which is fixed in the dev branch.

**Comment by wobba** [comment]
Issue is not following the issue templates. Seems this is a bug being reported rather than a question. Please provide exact steps for repro.

**Comment by paalolav** [comment]
On release 4.3 I also get the 500-error when sorting results by Title on a couple of tenants. Rolling back to 4.2 solved this for now.

**Comment by wobba** [comment]
@PratapAjaySolanki I tried to repro with the dev branch, but cannot repro in any of my test tenants, and created a doc named "subsea trees" which I have recall on for both queries.

**Comment by PratapAjaySolanki** [comment]
Thanks for your response @wobba 

I don't know if it can make a difference or not but I am using a SharePoint custom list in which we have few columns(choice column with dropdown and plain text field) which have this keyword "subsea trees".

**Comment by PratapAjaySolanki** [comment]
@paalolav Thanks for your comment.

I will check this and get back.

**Comment by wobba** [comment]
@PratapAjaySolanki which UX language are you using and does it work if you navigate to <site url> + "/_layouts/15/osssearchresults.aspx" and search there with the terms?

**Comment by PratapAjaySolanki** [comment]
Hi @wobba,

I am using English(en-us). I tried this osssearchresults.aspx page and it is returning the results for this keyword(subsea trees). Also I tried this in Search query tool, there also it is returning the results.

**Comment by wobba** [comment]
Can you grab the search request JSON and perhaps share? If it's consistent that it happens. Is this a multi-geo tenant? You need to compare the request from the query tool with what the web part does - and try to figure out the difference. As there has to be something different if one works and the other don't. You can switch the query tool to use POST instead of GET as well.

**Comment by MSchmittnaegel** [comment]
We're also experiencing the issue since last week. It seems that postquery response with 500 if the request takes longer than 12 seconds. When I hit refresh on our search page, 8 out of 10 times we get the 500 error. The few page loads without a 500 error have in common, that postquery responded in less than 12 seconds. 

It also seems to be related to the number of search results. Our query template applies on ~1,2mio items. As soon as I exclude one site collection with about 400k, postquery only takes 8 seconds and everything's fine again. It also doesn't seem to be related to what we are doing with the search webparts. Even we are only using search results with querytemplate * -> as soon as it takes > 12sec, we get 500.

Maybe related: We are also not able to load the "Selected properties" of the search results webpart any more. After 12 sec we see the 500 error in the network monitor. In this case it doesn't make any difference, which query template we use. I've tested it with one which should return any results: 
![image](https://user-images.githubusercontent.com/11876969/133284596-7362beba-46b4-479d-9d25-a40a7cd254ba.png)

For me, it seems to be some kind of backend issue. As soon as postquery is applied on a "large" number of results (IMHO 1,2mio shouldn't be considered as large), depending on the query it gets so slow that it runs into an internal timeout and response with 500.

**Comment by PratapAjaySolanki** [comment]
Hi @wobba,

I don't know what was the issue but I just removed all the search web parts from search page and reconfigure all search web parts with same configuration and it worked.
Thanks all for looking into this issue and all your supports which you provided.

**Comment by PikeSal** [comment]
Hard refresh (ctl+shift+r) in chrome fixed it for me

**Comment by Maya-Mostafa** [comment]
> On release 4.3 I also get the 500-error when sorting results by Title. Rolling back to 4.2 solved this for now.

I know this is an old issue, but with the latest PNP search version as of now  "4.11", I still get a server error when sorting with Title. I guess that since "Title" as a managed property is not sortable from the search schema definition, so, I assigned the title crawled properties to a RefinableString managed property which is sortable, and used that field in the sorting of the web part, and now I am not getting the error anymore.
I thought to share this solution here, it could help someone fix theirs.

**Comment by kasperbolarsen** [comment]
You are absolutely right, and you are not the first nor the last to be tripped by the fact that Title ain't sortable out of the box

https://www.m365thinking.com/post/fix-one-of-the-problems-in-sharepoint-search-make-title-sortable
