### ISSUE TITLE
PNP modern search results - show items from the an unique list

### ISSUE THREAD

**Issue by AnderOllive** [microsoft-search/pnp-modern-search#1334]
**Version used**
Ex: 4.3

**Question**
I Tried configure Query template to filter results in a unique list. 
{SearchBoxQuery}* path:	https://contoso.sharepoint.com/sites/site/Lists/nome da lista
I need to create a template where appear onlys fields only this list and i can't configure it.
Result are shown how to card. Each item is a card, but i need a card that show all items by line.

**Screenshots**
![image](https://user-images.githubusercontent.com/88772391/134502416-f966a484-7cbc-4962-b8e9-9668732c413a.png)

I Need see a card shown item by item of the list per line
![image](https://user-images.githubusercontent.com/88772391/134502552-5d03984d-32c6-4d03-8332-7c19c2c96810.png)

**Comment by wobba** [comment]
`{SearchBoxQuery}* path:"https://contoso.sharepoint.com/sites/site/Lists/nome da lista"`

**Comment by AnderOllive** [comment]
@wobba I use this query {SearchBoxQuery}* path:"https://contoso.sharepoint.com/sites/site/Lists/nome da lista", but my problem now is. I don't can insert the columns with an item. EX:
title
link
image

**Comment by wobba** [comment]
That's a question of SharePoint column to crawled property to managed property mapping. See https://docs.microsoft.com/en-us/microsoft-365/community/how-do-site-columns-become-managed-properties-thus-available-for-search and  https://docs.microsoft.com/en-us/sharepoint/manage-search-schema for some information. A bit outside what we cover directly in this project, and it's the same process as it's been since SharePoint 2013 was released.

And the new Image column in SharePoint is not supported in search at the moment.

**Comment by AnderOllive** [comment]
@wobba thank you, I will study this theme and I'll verify the better solution for my case :)
