### ISSUE TITLE
Excel icons not loading in Search Results for preview

### ISSUE THREAD

**Issue by billr-stcu** [microsoft-search/pnp-modern-search#135]
**Version used**
3.10.0

**Describe the bug**
When search results are displayed, the preview icon for Excel documents does not always display. In fact, it rarely displays.

**To Reproduce**
1. Search results includes Excel documents

**Expected behavior**
Expect that the icon would display. We can still click on the broken image icon and see the preview.

**Screenshots**
![image](https://user-images.githubusercontent.com/58996868/77120877-1e098380-69f7-11ea-8615-448a823072ca.png)

**Desktop (please complete the following information):**
Chrome

**Additional context**
SharePoint Online

**Comment by FranckyC** [comment]
Hi @billr-stcu. Actually this behavior is caused by the search response itself. For an unknown reason, Excel files don't get a preview value in the `ServerRedirectedPreviewURL` managed property like other Office documents do. I added a default image when this occurs. Not the best but I can't really do much.

**Comment by wobba** [comment]
@FranckyC  We could perhaps change to use the same preview/thumbnail function as we use in the card layout?

**Comment by FranckyC** [comment]
Doesn't work..
