### ISSUE TITLE
Dynamic Query in Modern Search Webpart

### ISSUE THREAD

**Issue by deepak363** [microsoft-search/pnp-modern-search#1424]
Hi All,

I using modern search webpart and implemented custom search suggestion on my "PnP - Search Box" webpart with the help below tutorial -

https://microsoft-search.github.io/pnp-modern-search/extensibility/custom_suggestions_provider/

Now the problem is how can i pass parameter to my custom suggestion provider Library so that i can write dynamic query and return the result from suggestion provider based on my input value.

Any help would be appreciated!

Thanks

**Comment by deepak363** [comment]
> You have the `queryText` parameter in the `getSuggestions` method which is the input value from the search box. From here, you can do anything you want.
> 
> ```
> public async getSuggestions(queryText: string): Promise<ISuggestion[]> {
>         // Do whatever you want with 'queryText'
>  }
> ```
> ```

Instead of input value from searchbox How can pass my webpart property value as "Query text". I have one dropdown let say country so how can i pass dropdown selected value as input?

**Comment by FranckyC** [comment]
Ok not sure I get it. Let's go step by step:

> How can pass my webpart property value as "Query text"

What Web Part property you are refering to? When you say 'query text', are you takling about the value in the search box, or the `{searchTerms}` value in the Search Results Web Part?

> I have one dropdown let say country so how can i pass dropdown selected value as input?

Where did you define this input? Can you explain a little bit the expected behavior you are implementing?
