### ISSUE TITLE
Web part PnP - Search Verticals doesn't load

### ISSUE THREAD

**Issue by sherpas-par** [microsoft-search/pnp-modern-search#1643]
**Version used**
4.5.0.0

**Describe the bug**
After upgrading to PnP Modern Search 4.5.0.0 the web part **PnP - Search Verticals** doesn't load. A colleague of mine has the same problem in another tenant. Even if we remove the web part and add it again the same problem occurs.

**To Reproduce**
1. Edit page
2. Click on + to add web part
3. Add web part 'Pnp - Search Verticals'
4. See screenshot for error message

**Expected behavior**
I expect that PnP - Search Verticals web part load correctly as in previous version of PnP - Modern Search

**Screenshots**
![image](https://user-images.githubusercontent.com/57943258/146152833-ed29a67e-0e24-43b0-be16-ae72c49a24d2.png)

**Desktop (please complete the following information):**
 - Browser [Microsoft Edge (Chromium)]

**Comment by wobba** [comment]
Can you try `localstorage.clear()` and `sessionStorage.clear()`? When updating sppkg files these issues are known to be encountered and will resolve themselves once caches are flushed. Which means if you use CDN that is a dependency as well. Or try in an anonymous browser.

Removing/adding web part does not resolve this. You can try to delete and re-upload the sppkg. Sometimes that makes it work "quicker".

As a general rule updating sppkg outside of working hours is a good idea due to these caching issues.

**Comment by FranckyC** [comment]
Seems a missing translation. What is the UI language? Can you try with english?

**Comment by sherpas-par** [comment]
@FranckyC, you are right! Changed default language in Microsoft Edge from Swedish to English and then PnP - Search Verticals can be added.
![image](https://user-images.githubusercontent.com/57943258/146193860-1ec0380e-d32e-4a06-b0be-497f140a8f50.png)

**Comment by FranckyC** [comment]
This will be fixed in the next release. Sorry for that :/

**Comment by FranckyC** [comment]
Should be resolved with 4.5.1 version.

**Comment by sherpas-par** [comment]
Thanks for insanly fast fix - will try 4.51 in a moment.

**Comment by sherpas-par** [comment]
Works like a charm, thanks once again 👍
