### ISSUE TITLE
Search Results: special characters in HitHighlightedSummary

### ISSUE THREAD

**Issue by h-h-o** [microsoft-search/pnp-modern-search#1696]
**Version used**
4.5.3.0

**Describe the bug**
In the Search Results web part, some special characters in the HitHighlightedSummary field are not displayed correctly.
For example, the character ï is displayed as Ã¯
Same problem for some other characters, but I don't have a list of all characters that are displayed incorrectly.

**To Reproduce**
- I'm using a Communications site
- Create a News post and use the character ï in the summary text
- In the Search Results web part, configure one of the layout slots to use the HitHighlightedSummary field
- Select a layout that uses this slot field or add it to your custom layout

**Expected behavior**
Special characters are displayed as entered on the Page

**Desktop**
Windows 10, all browsers (Firefox, Edge, Chrome

**Additional context**
SharePoint Online
I'm using a custom layout, but the same problem exists with the default layouts.

**Comment by wobba** [comment]
Can you verify that the data looks ok in the response JSON coming back first? To validate it's an encoding/parsing issue in the web part and not an API issue.

**Comment by h-h-o** [comment]
I checked the JSON response and special characters in HitHighlightedSummary contain the same incorrect encoding values. So it looks like an API issue.
Thank you for your help.

**Comment by OliverR-82** [comment]
Hi, I realize that this is an older issue that has been closed, and I apologize for bringing this up again, but I thought it was better than to raise a new issue.

I was wondering if there is any way to get around this? We are facing the same problem with pretty much any accented characters. Is there any way to change the encoding of the page somewhere so that the characters show up correctly in the Search Results web part? The customer where we're facing this issue is Dutch speaking, but I can imagine that for French speaking users the problem will occur even more frequently since they use a lot of é, è, à, ç, ê, ô and so on.

Is there any way at all to remedy this?

**Comment by kasperbolarsen** [comment]
Yes, there is a way to fix this,  but it will require you to file an error report with Microsoft as this is an API error.
