### ISSUE TITLE
Paging and sortable fields

### ISSUE THREAD

**Issue by bezua** [microsoft-search/pnp-modern-search#177]
**Version used**
3.7, 3.11.1

**Describe the bug**
Playing with page numbers below the search results web part does not always preserve sorting settings. Please see scenarios below
**To Reproduce**
[Scenario 1]
1. Use search results web part displaying results in detailed list layout
2. Configure web part to use sortable field - let's call it XField
3. Run a query to get multi-paged result
4. Sort it by XFieldZA order.
5. Click page 2, then page 3. Everything is fine
6. Now click on the page 1. Results are not sorted anymore. 
It was expected to get first result page sorted by XField ZA

[Scenario 2]
1. Use search results web part displaying results in detailed list layout
2. Configure web part to use sortable field - let's call it XField
3. Run a query to get multi-paged result
4. Sort it by XFieldZA order.
5. Go to page 3 directly. Everything is fine
6. This time sort it by AZ. It goes automatically to page numer 1. That's fine.
7. Go to page 3 directly. Something is wrong, we went back to page number 1 and sorted order is gone.
It was expected to get third result page sorted by XField AZ

**Expected behavior**
Described above.

**Screenshots**

**Desktop (please complete the following information):**
tested on chrome
**Additional context**

**Comment by bezua** [comment]
Scenario 2 is fixed with
https://github.com/microsoft-search/pnp-modern-search/pull/183

**Comment by wobba** [comment]
So, scenario 1 is still an issue?

**Comment by bezua** [comment]
yes, scenario 1 is still an issue.
It's somewhere between SearchResultsContainer and SearchService.
SearchService has a special treatment for page number 1 (not sure why, at least for now).

**Comment by gunner13** [comment]
I got the same issue so I did some investigations and I found that the SearchService calls 
"this._localPnPSetup.search(searchQuery)" when page = 1 and "this._initialSearchResult.getPage(page, this._resultsCount);" when page > 1

I believe if it was "this._localPnPSetup.search(searchQuery)" for both cases, sorting would have not worked for any pages.

The issue is from the SearchResultsWebPart.ts file. In detail, render function of the web part get called every time we click on a page number. As a result, the renderCompleted function get called to, this function updates the SearchService based on Web Part Properties, therefore, SearchService.SortList will be the same as Web Part SortList property, the Web Part SortList property is never changed by code, it's always reflect what user configured on the Property Pane.
My solution is adjusting the renderCompleted function to not change the SearchService.SortList if it has existing value before and let the SearchResultsContainer decides its value in the ComponentDidUpdate function. 

This's what I applied in my fork, hope this will help you somewhat.

**Comment by wobba** [comment]
@gunner13 would be great if you submit a PR

**Comment by gunner13** [comment]
I will, but this fix based on fixes of two other sorting issues. One has been posted yesterday, I will post the other one soon and paste their links here, then create a PR so that you can review.

**Comment by gunner13** [comment]
I created a Pull Request for this issue, however, as I said earlier, this Pull Request is based on commits of two other issues about sorting posted by me too:
https://github.com/microsoft-search/pnp-modern-search/issues/197
https://github.com/microsoft-search/pnp-modern-search/issues/214
These two issues have two separate PRs though. 
Hope this helps.
