### ISSUE TITLE
PnP Search Filters v4 - 0 Results when filtering on multi-user

### ISSUE THREAD

**Issue by ileana2019** [microsoft-search/pnp-modern-search#2096]
**Version used**
Ex: 4.5.2.0

**Describe the bug**
I have a RefinableString that is linked to a multi-user field in SharePoint. I get the ReifnableString results inside the Search Results and Search Filters webparts. However, when I try to filter, I get 0 results (even if I see the number of results for that filter value inside the Search Filters webpart).

**To Reproduce**
1. Add the Search Results and Search Filters webparts to a page
2. Connect the 2 webparts
3. Configure a RefinableString to get data from a multi-user crawled property
4. Display the RefinableString inside the Search Results and Search Filters webpart
5. Filter on the RefinableString

**Expected behavior**
When filtering on the RefinableString, the Search Results should display the number of results that are in the brackets for that filter.

**Screenshots**
![RefinableString](https://user-images.githubusercontent.com/55545989/169268197-a3130c01-fe65-4889-b024-8b45e63bda57.PNG)

![Search Results](https://user-images.githubusercontent.com/55545989/169268243-4656dad3-07b2-4ec5-bc2e-70f1c07b5ab2.PNG)

![Search Filters](https://user-images.githubusercontent.com/55545989/169268284-1e7fc5c2-3f11-49d3-abf8-8ad4e785a456.PNG)

![Search Results 2](https://user-images.githubusercontent.com/55545989/169268340-b8f3b3ae-aa51-448f-8287-3fe2aa028af3.PNG)

![Search Filters2](https://user-images.githubusercontent.com/55545989/169268396-aa7442d5-fc63-4d35-89dc-4c6087bb7172.PNG)

**Desktop (please complete the following information):**
 - Browser Chrome

**Additional context**

**Comment by FranckyC** [comment]
Hi, I'm able to reproduce this issue using a multi value people column and using the ows_q_USER crawled property with a RefinableString managed property. However, it works fine with the default ows_q_USER_Author property. Is your column multi value by any chance?
I can't really tell what would be the issue as we use the refinement token provided by the API response with no modification. If I use this token with SharePoint Search Query tool, I get no result as well. As a workaround you can use the regular `ows_` text crawled property:

![image](https://user-images.githubusercontent.com/5659122/169709333-d7e0d7c6-001f-4c14-af74-4ee57eb366a7.png)

**Comment by ileana2019** [comment]
Hi @FranckyC ,
Thank you for your reply! Indeed, the user field is a multi value field. Adding the crawl property "ows_[MultiUserFieldName]" to the RefinableString and removing the crawl property  "ows_q_USER_[MultiUserFieldName]" works now to filter (I get results if I filter on the values); However, if the field contains more that 1 user (since it is a multi value user field), then the filters are displayed in double:
![Owner](https://user-images.githubusercontent.com/55545989/169855078-60b1f58d-5276-4512-9c41-2a4470b85641.PNG)

I added also the crawl property "ows_q_USER_Author" to another RefinableString, and try to filter the search results, but still no result is found. So also that it is not working for me.

**Comment by FranckyC** [comment]
Seems to be an API issue as multi values should be handled server side and split into single entries in the response. @wobba  can you confirm?

**Comment by wobba** [comment]
@FranckyC it's an API issue and will report once I know more.

**Comment by wobba** [comment]
The issue was identified internally and a fix is made. Should roll out over the next weeks.

**Comment by ileana2019** [comment]
Is this issue solved in v4.7?

**Comment by wobba** [comment]
@ileana2019 API issue, not web part issue.

**Comment by wobba** [comment]
Depending on web part version it could be related to the newly logged https://github.com/SharePoint/sp-dev-docs/issues/8443

**Comment by yvsuhas** [comment]
Hi @wobba, do you know if this fix is rolled out to all tenants as I still see the issue in Microsoft search filters that were configured under a custom vertical using OOTB setting and the same issue occurs in case of PnP Search Filter webpart as well?

**Comment by wobba** [comment]
@yvsuhas I recommend logging a new support case if it's still not resolved. Or comment on the above sp-dev-docs issue.

**Comment by yvsuhas** [comment]
Hi @wobba, we've raised a support case with Microsoft and received the following response:

Detailed problem statement: When we try to filter the search results, the available options in the dropdown are shown in the format that is stored in the library instead of showing single values for the person or group column and it displays correct values (single values) for the managed metadata field

Our support escalations has identified the behavior as by design. Unfortunately, we don't have any workarounds for this issue at this moment however you can certainly provide your Product Feedback and Suggestions on the link below as many features of the current program were designed and upgraded based on customer feedback.

Any thoughts?

**Comment by JoeAyre** [comment]
Hi @wobba  - same issue in our tenant in Australia. The filter returned the people fine, it's just that if more than one person is added, they should in a concatenated line e.g., user1;user2;user3. I had hoped (and kind of expected) that they would be shown as separate filters i.e., as separate selectable check boxes to refine the results on e.g., user1.

Be great if you could advise on what (if anything) can be done to get the desired behaviour.
Thanks as always,
Joe

**Comment by JoeAyre** [comment]
Hi @wobba @FranckyC 
I revisited this issue to see if any change had occured and it seems there has been a slight change.
When I map a multi value person column to a refinablestringXX using the OWS_Q_USER_<NameOfColumn> crawled property, and then use the refinablestringXX in the filters web part, it no longer concatenates all the users, and just shows single users. The problem is though that it displays too much information about that user. Ideally it would just show the display name, but instead it shows e.g.,

FirstName.LastName@thedomain.com | LastName, FirstName | ABCDEF1234567890ABCDEF1234567890ABCDEF1234567890ABCDEF1234567890ABCDEF123456 i:0#.f|membership|FirstName.LastName@thedomain.com

It would be great it there was a way to modify this so that it just shows e.g., FirstName LastName.

Any suggestions would be welcome.
Thanks.
