### ISSUE TITLE
"Modified" refiner manager property

### ISSUE THREAD

**Issue by Narasireddy447** [microsoft-search/pnp-modern-search#228]
I would like to configure "Modifed" in Refiner. i have modified "RefinedDateXX" managed property and used "owsModifed" crawled propery. but still not able to see Modified in refiner panel. 
please help to use "Modified" in refiner

**Comment by wobba** [comment]
Have you recrawled all the content to ensure there is a value in RefinableDateXX? There are information out on my blog and others on how to troubleshoot search, and I have aggregated much of it in https://www.amazon.com/Troubleshooting-Search-SharePoint-Online-solving-ebook/dp/B082FMGSZY as well.

I suggest you start using PnP PowerShell or the SharePoint Query Tool so you know what data a particular item has. That's the place to start. Your issue is most likely with understanding search and indexing, and not with the web parts.

If you managed to get the data working in classic SP search experiences, and not in these web parts, then it's web part related.

**Comment by saregbesola** [comment]
@Narasireddy447 , I don't know if you already have this working. But if you want modified in the refiner you don't need to use any RefinableDateXX, just use LastModifiedTime managed property. This is already mapped to owsLastModifiedTime.

**Comment by wobba** [comment]
Closed due to lack of author input.
