### ISSUE TITLE
Filter Web Part - Edit Filter Field not linking to Datasource (Static field only)

### ISSUE THREAD

**Issue by StarsandPlanets99** [microsoft-search/pnp-modern-search#2419]
**Version used**
4.7

**Describe the bug**
For the filters web part, when selecting Edit filters the drop down for the filter Fields do not display

**To Reproduce**
Copy these instructions
https://microsoft-search.github.io/pnp-modern-search/scenarios/page-with-filters/

**Expected behavior**
The Edit filters, Filter field should have drop downs

**Screenshots**
![image](https://user-images.githubusercontent.com/115179834/194380871-a520d493-fbff-4077-8082-e6f8bb5553e8.png)

![image](https://user-images.githubusercontent.com/115179834/194381278-826934f9-bcfc-4732-93f0-20d83d4f268f.png)

![image](https://user-images.githubusercontent.com/115179834/194381362-dca8dfac-18f2-4f37-9282-26a5f3d3e0fb.png)

![image](https://user-images.githubusercontent.com/115179834/194381992-c5b3e110-1377-4614-a474-b0547fe99c92.png)

**Desktop (please complete the following information):**
 - Browser  - tried Chrome and Edge

**Additional context**

**Comment by FranckyC** [comment]
Hi @StarsandPlanets99, this is the expected behavior. Fields are listed according to the results and because you don't have any results currently displayed, no filters can be deduced. Try to put a base query like "*" and retry. You can also enter the property name directly in the text field and press "Enter" to add it as filter.

**Comment by FranckyC** [comment]
@StarsandPlanets99 see my comment above to know why fields are not showing up. For your other issue, this is because the **CreatedBy** property is not set as "Refinable" in the search schema. To use it you must configure and existing "RefinableStringXXX" property and map the crawled properties:
![image](https://user-images.githubusercontent.com/5659122/194412124-aeaef9b1-876a-4486-b2cc-474e8dfc1945.png)

**Comment by StarsandPlanets99** [comment]
Ok Thanks
Actually the * as the default value fixed it

"Try to put a base query like "*" and retry. " Thanks @FranckyC 

Can I suggest that the tutorial page is updated please? 
https://microsoft-search.github.io/pnp-modern-search/scenarios/page-with-filters/

I now see the dropdowns. Thanks so much for your suggestion 

![image](https://user-images.githubusercontent.com/115179834/194415083-ed925462-9e6b-4aaa-be45-4f95aa25c7b5.png)
