### ISSUE TITLE
No dropdown for Filter Field on Pnp Search Filter Webpart

### ISSUE THREAD

**Issue by GitMrsPeel** [microsoft-search/pnp-modern-search#2605]
**Version used**
Ex: 4.8

**Describe the bug**
I have added the search box, search results and search filter web parts.  The search box pushes results to the search results so this works.  On trying to setup filtering I find I do not have a drop down showing when I go to customize filters.  The 'Filter Field' in every piece of documentation and video/tutorial I have watched has a drop down for you to choose from.  However, I am not presented with a dropdown.  I have included a screenshot.  The PnP Search results web part has the default 'selected properties' showing and  I have not altered these.   
I find I can get filtering to work when I manually type in some default properties (for example Author seems to work).  The field remains like 'free text' rather than a dropdown.    
I experienced this with version 4.7 and upgraded to 4.8 in the hope it was a a verison problem.  However, with 4.8 I have the same issue.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Go to PnP - Search Filters
2. Scroll down to 'Customize filters'
3.  Click 'edit'
4. The second field along called 'Filter field' does not have a drop down.

**Expected behavior**
Filter field should have a drop down for me to select from

**Screenshots**
Screenshot is added
![image](https://user-images.githubusercontent.com/21196074/204552475-a390094b-ca6c-4fe4-a129-96a1da3750a3.png)

**Desktop (please complete the following information):**
 -Chrome Version 107.0.5304.108 (Official Build) (64-bit)

**Additional context**

**Comment by edarroudi** [comment]
Did you connect both filter and result webpart with each other?
FilterWebpart: 
![image](https://user-images.githubusercontent.com/935493/204742036-81aaa0dc-4ea9-40b1-a317-cb3c68dcfa65.png)

That should do it.
And of course connect the other way as well
![image](https://user-images.githubusercontent.com/935493/204742653-70d670d5-c92a-4288-841f-cee6d7e1e46f.png)

**Comment by FranckyC** [comment]
Hi @GitMrsPeel , the reason why you don't see any values in the dropdown is because the search results Web Part does not have any results to display at the time you configure filters. Values are dynamic and deduced from current results in order to help you to choose the correct managed property, that is not a static list. However, you can still type your own value and press 'Enter' to use the desired field.

**Comment by GitMrsPeel** [comment]
Hello both, Thank you for your replies.  I can confirm that the results part is connected to the filter and vice versa.  @FranckyC I don't really follow this as every tutorial and screenshot I have seen (even users starting from scratch) have the dropdown.  I have had some success adding 'author' manually, but at what point would you expect the drop down to become available?  It's difficult to try to configure without this list.  If I try to reconfigure after carrying out searches there is still no dropdown.

**Comment by wobba** [comment]
@GitMrsPeel we have no control if the API request which populates the dropdown will work or not - so nothing we can control. I'm thinking of replacing it with a static list instead to avoid these questions/issues as the non-API we use is undocumented and not robust.

**Comment by wobba** [comment]
I might remove this feature or have a pre-made list of properties. This is how it works today to see some values:

* Ensure you have results showing in the result web part
* Configure the filter web part, and it will display the list of properties returned with the results

This is not very helpful, as most of these are not refinable, so keeping it free-text is the best approach. Especially since the "API" we use to get a list of properties is not a real API and often fails.
