### ISSUE TITLE
Page navigation of Pnp search results not working in Teams

### ISSUE THREAD

**Issue by Romain-eXalt** [microsoft-search/pnp-modern-search#2694]
Hello everyone,

I'm using the latest version of PnP Search but I'm facing an issue when using Teams (the app, not the browser) : the button to navigate through the page results do not work. Maybe I'm missing something here ? On browser it works perfectly fine.

**The Bug**
When using teams, if I have a lot of results in my PnP Search Results, then some page navigation 1  2  3  4 ... appear, which is fine.
However, when I click on any page number nothing changes, it stays on page 1 only.

<img width="98" alt="image" src="https://user-images.githubusercontent.com/115587346/212503805-88395903-57a9-45dd-b2cc-5207f8372afc.png">

**To Reproduce**
1. Create any search results with several page results
2. Open Teams on premise (the application, not through the web browser)
3. Click on page 2 or 3 or 4 ...
4. Nothing happens

**Expected behavior**
That the page results should change (when using a navigator it works perfectly well).

Many thanks & regards,
Romain

**Comment by kasperbolarsen** [comment]
Hi @Romain-eXalt, I have tried to reproduce that error, and can confirm the issue. However in my test the issue is also present in the Browser ( Edge, Version 108.0.1462.76)                                   
It doesn't matter if the Home page of the SharePoint site is added using "SharePoint" or "SharePoint Pages), both has this issue.

![image](https://user-images.githubusercontent.com/20593570/212627062-8288be12-a19a-492b-b29d-4addc1f5db39.png)

**Comment by Romain-eXalt** [comment]
Yes you are right, both have the issue indeed !
