### ISSUE TITLE
Refiner Improvement: Apply Button on top of Multi-Value Refiner

### ISSUE THREAD

**Issue by engineererr** [microsoft-search/pnp-modern-search#272]
We configured a refiner called "Author". There are more than 100 possible authors. The refiner list is very long. That's ok for us. But we haven't found the "Apply" button at first. Users see the button only if they scroll far down - what they don't. So they click a refiner value, collapse the author refiner and have their refiner selection deleted.

I suggest changing the display template to render the apply button before the refiner values. 
A possibility as well would be to render the button twice maybe - top and bottom.

File to change: https://github.com/microsoft-search/pnp-modern-search/blob/master/search-parts/src/webparts/searchRefiners/components/Templates/Checkbox/CheckboxTemplate.tsx#L79

**Comment by FranckyC** [comment]
Hi @engineererr, good suggestion, feel free to make a PR on this. The 'Apply' button could be displayed on top when too many values are displayed using an arbitrary count or better, when at least one value is selected.

**Comment by Georg-Trixl** [comment]
Yes I would love to have an "Apply" at the top, because of descending sorting the most interesting things are at the top, but anyway to have "Apply" on bottom - if you already scrolled down makes also sense.

If could place a wish, I'd go for top and bottom placement together or an option to configure it.
