### ISSUE TITLE
Refiner Improvement: only show max number of refinement values 

### ISSUE THREAD

**Issue by eldoro80** [microsoft-search/pnp-modern-search#279]
I'm very happy using the pnp-modern-search solution. However, I'm encountering  a scenario in which to many values are diplayed in a specific refiner. The other refiners are out of sight and users have to scroll down....

I'd love for an improvement in which I can set the number of values that are shown per refiner. When setting this 'limit' there has to be a way to navigate through the values. And the refiner filter offcourse has to filter all values.

Keep up the good work!

**Comment by FranckyC** [comment]
Hi @eldoro80 , using the default refinement item template, you can now search for specific values instead of scrolling down. 

![image](https://user-images.githubusercontent.com/5659122/82702696-80be0c00-9c40-11ea-83b2-33e1af8c5a66.png)

![image](https://user-images.githubusercontent.com/5659122/82702781-aea35080-9c40-11ea-90bc-b4859df62302.png)

If you use multiple filters with a lot of value, maybe you should also set them as collapsed by default.

**Comment by eldoro80** [comment]
> Hi @eldoro80 , using the default refinement item template, you can now search for specific values instead of scrolling down.
> 
> ![image](https://user-images.githubusercontent.com/5659122/82702696-80be0c00-9c40-11ea-83b2-33e1af8c5a66.png)
> 
> ![image](https://user-images.githubusercontent.com/5659122/82702781-aea35080-9c40-11ea-90bc-b4859df62302.png)
> 
> If you use multiple filters with a lot of values, maybe you should also set them as collapsed by default.

@FranckyC  thanks for your reply. I know I can collapse the refiner and search the values. That helps, but it's nog the ideal solution. I want users to see all refiners and have a sense of what values are available in them. So they can easily choose how to refine

**Comment by wobba** [comment]
My rudimentary research in the past has shown refiner type below the third is seldom used. Too many values is also not ideal, hence the filter box. I suggest you move the one refiner with too many values to the bottom to give more space to the others.
