### ISSUE TITLE
Add support for Timezones when searching by Date

### ISSUE THREAD

**Issue by RayMK42** [microsoft-search/pnp-modern-search#28]
**Category**
- [ ] Question
- [ ] Bug
- [x] Enhancement

**Version used** : 3.7.0

----------------------------------------------
  

As you probably already known, when persisting the value of a Date column on a list/library SharePoint internally converts the date to UTC format. This means that for some time zones, the date part of the stored DateTime object can in some case be different from what is displayed in the UI for some users (depending on the site time zone and their personal overrides)

As an example, if a site is configured to use an UTC+3 timezone, a date inserted as "2019-01-01 (00:00)" will actually be stored as "**2018-12-31** (21:00)".

When performing a Date based search on a Date managed property (example "Date00:2019-01-01) the search rest api by default assumes that the date is provided as an UTC date. This causes some issue for users working in non-UTC time zones: in the above example, no result is found if an users search for 2019-01-01. Obviously this cause a lot of confusion.

Looking at how the various search api operates I notice that this behavior can be changed by specifying an additional parameter called "**TimeZoneId**" in the search request. Apparently this parameter isn't documented on MSDN, but I noticed it was used in [another GitHub project - PnP-PowerShell](https://github.com/SharePoint/PnP-PowerShell/blob/master/Commands/Search/SubmitSearchQuery.cs). I was successfully able to replay with Fiddler one of the call to the _api/search/postQuery endpoint made by the Search webpart and just adding the parameter with the correct timezone identifier (gotten from [here](https://blog.jussipalo.com/2013/10/list-of-sharepoint-timezoneid-values.html)) was enough to still get the expected results when using the local date as a search parameter.

I was therefore thinking that it shouldn't be to hard to add a new configuration parameter to the Search Results web part that would use the aforementioned parameter to enable time zone support for date based search operations. As far as my understanding goes, the pageContext object already used by the search service to fetch the current locale should also include information about the current time zone, so it should be possible to get that info and use it to populate the TimeZoneId parameter.

I would try and provide an enhancement myself, but right now I fear I lack full understanding of the project structure, so I don't think I am up to the task. 

Could you please review this suggestion and see if implementing this new feature seems viable for you? As far as I can tell, this seems to be a common problem for many users, so having support for timezone-aware search could be a big "selling point" for this project.

**Comment by FranckyC** [comment]
Hi @RayMK42, thank you for your feedback. I will think about it for the next version forsur. Should be a small update if the timezone is available from the page context.

**Comment by dcashpeterson** [comment]
@FranckyC I had a similar issue using a custom template and the templating options for the built in formatting. When you render the date using getDate it comes back without the Z at the end so it doesn't understand the local formatting as indicated in the documentation. For example, If you render {{EventDateOWSDATE}} it returns 2019-12-17T16:00:00.0000000. The event was created in EST so it is -5 UTC and should read 11 am EST. If you render that field using {{ getDate EventDateOWSDATE "MM DD h:mm a" 0 }} the expectation is that it should read Dec 17 11:00 but instead it reads Dec 17 4:00pm. In order to get the time formatting to work correctly you need the Z at the end. I checked what is coming back from search using the Search Query Tool and the Z is part of the data that is being returned from search. Is there a good way of dealing with this to show the time of an event using the local time zone?

**Comment by FranckyC** [comment]
@dcashpeterson The documentations says with the '0' value for the last parameter, the browser time zone will be use. Try to use the web time zone ('3') or user time zone ('4') to see if there any difference.

**Comment by FranckyC** [comment]
@RayMK42 should be resolved by #63 . Feel free to checkout the develop branch and test.
