### ISSUE TITLE
Parameterized Search Page linked from Megamenu

### ISSUE THREAD

**Issue by melkinsco** [microsoft-search/pnp-modern-search#302]
I realize this isn't per se an issue with the web parts, but wondering if anyone has solved this issue.  We are using a single search page, with search criteria passed to the page via the URL.  The problem we have is that, once the user clicks a link in the menu, and loads the page the first time, subsequent clicks of other links do not reload the same page with the new parameters.  Clicking the links does...nothing.  A refresh is required to click the new link.  Not a great experience for the user.

Thanks!

**Comment by MakingThingsWorkToronto** [comment]
Can you elaborate on the specific link you’re referring to?

Pages in modern do not go through a full page refresh cycle but rather reload sections. 

If you want to force a full page reload on a custom hyperlink you can add an attribute called data-interception=‘off’.

There was an issue on a previous release where I saw behaviour similar to what you’re suggesting however it disappeared. To work around it I set the data-interception attribute to force a full page refresh. You likely want to make sure you’re on the most recent version (read release notes as there are breaking changes).

See more here: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/hyperlinking

**Comment by melkinsco** [comment]
Thanks for the quick reply!
Example of a link to Dental Benfits:
.../BenefitsSearch.aspx?BenefitTopic=Dental&data-interception="off"
Swap Dental for Vision and that would be a link to a page with Vision Benefits.  As you can see, the data-interception is set to off.
We're on version 3.12.0.0

3.12.0.0
--




3.12.0.0
--

**Comment by wobba** [comment]
`data-interception=off` should be a parameter on the `<a>` tag, not part of href.

`<a href="some url" data-interception="off">text</a>`

**Comment by sstrache** [comment]
Hello.  I work with melkinsco.   Thank you for the recommendation.   Unfortunately the modern menu structure only allows us to set an 'address' field (href value).  We can't add additional <a> tag attributes.  Have you seen the PNP web parts working in conjunction with the modern menu system using URL parameters?   Is there some modern site configuration we are perhaps missing that allows the menus to work?   

Thank you.

**Comment by wobba** [comment]
@FranckyC could we implement something like https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/intercepting-query-changes-in-webparts? Would we need special logic regarding if it's tied to a search box or not.

**Comment by saregbesola** [comment]
@wobba  we are also experiencing the same issue. In addition to the issue raised by @melkinsco , we also notice that when you redirect the search box in the suite bar to a custom result page, it works fine from any other page/site except the result page. While on the custom result page if you search using the suite bar search box, it doesn't work as the page does not reload. Kindly look into that too. 

Thanks

**Comment by wobba** [comment]
Search box is related to #325

**Comment by saregbesola** [comment]
> Search box issue is most likely related to #325

@wobba it's not. I have just installed the newer version you published today, the bad request error has been fixed, kudos! But the the issue with the search box still persists. The search box issue is similar to the way the link in the Mega menu works while on the custom result page. I think the issue is how someone explains above that "Pages in modern do not go through a full page refresh cycle but rather reload sections." This makes logical sense as the search box has been configured to send result to the custom result page and since you are already on the custom page there is no full page reload, it instead just updates the query string section of the url without reloading the page. So it will be nice if the PnP Search Result web part can detect changes in the url to refresh its result. I'm looking at this possibility as well if I can do it at my end.
