### ISSUE TITLE
HeaderlessSearchResults Is Limited to One Page

### ISSUE THREAD

**Issue by HiltonGiesenow** [microsoft-search/pnp-modern-search#307]
The HeaderlessSearchResults layout is great for **the** search page, but what if we have multiple, to handle different search-based apps, or verticals? If we set any other pages, even if they are "Search" pages, to use HeaderlessSearchResults, they will give an error because they are of course cannot *all* be defined as "the" search results page for the site

**Comment by wobba** [comment]
This should be logged at sp-dev-docs, and it's intentional. It's mimic'ing how oob search works with one search application only. If you have navigation entries on your search page, you need to build it all into the same page - similar to what the PnP Modern Search Vertical web part allows you to do.
