### ISSUE TITLE
Date range filter does not accept same date in From and To in PnP Search Filter. Is it as per design? or bug? someone  please assist  

### ISSUE THREAD

**Issue by ranjithraj06** [microsoft-search/pnp-modern-search#3075]
Date range filter does not accepts same date in From and To in PnP Search Filter. Is it as per design? or bug? someone  please assist .
I am using PnP search webpart v4.7

**Comment by srinutamada** [comment]
This is very important for us as user's filters content based on date ranges and sometimes to see data for a specific date.

**Comment by ranjithraj06** [comment]
> Can you please fill in the issue template, it's there for a reason. Version, steps for repro, possible screenshots etc. If not the issue will be closed.

Sure @wobba I will share the issue template with the details. Thanks for considering this issue.

**Comment by ranjithraj06** [comment]
![image](https://github.com/microsoft-search/pnp-modern-search/assets/63115197/194f2db8-3c39-44c2-aaf2-be2d7336e9f7)

**Comment by ranjithraj06** [comment]
@wobba Could you please have a look on the Issue details I have provided above and help us?

**Comment by ranjithraj06** [comment]
@wobba Could you please help on this issue?

**Comment by wobba** [comment]
This is by design and not a bug as the query is created like below with from Greater than or Equal, to Less than or Equal. And it's exact on the hour - which may or may not be a good thing. So to capture 24h, you need to pick two dates today. Feel free to log an improvement suggestion. And time zones + zero date makes it somewhat tricky to work for 100% of all cases.

`Created:range(2023-06-20T22:00:00.000Z,2023-06-21T22:00:00.000Z,from="GE",to="LE")`
