### ISSUE TITLE
Refiners Improvements

### ISSUE THREAD

**Issue by coupalm** [microsoft-search/pnp-modern-search#36]
Refiners: Display hierarchical structure of managed metadata terms (like [Elio Struyf refiners example](https://github.com/SPCSR/DisplayTemplates/tree/master/Search%20Display%20Templates/Refiners/Managed%20metadate%20refiner))
Refiners: Display description of managed metadata terms on mouse hover terms

**Comment by FranckyC** [comment]
Thanks for the input @coupalm. Definetively a good improvement. I will look into this when have time.

**Comment by quarterhorse** [comment]
This would be very helpful and useful, particularly with deep and wide structures like geopolitical decompositions [region/country/state-province like ISO-3166].  Single and multi-select, too.

**Comment by maru-sama** [comment]
I also give a thumbs up for a hierarchical structure of the metadata, right now we are only able to use the try like structure in the filters pane of the modern view experience. It would be perfect if we could use this on search page as well, to "drill-down" to our various geographic locations

**Comment by wobba** [comment]
From an end user perspective I don't belive this is a great way to navigate/filter. But it all depends on the number of items per level. As a technical ability I agree, but would be hesitant to use this for a customer for most scenarios. My personal opinion 🙂

**Comment by maru-sama** [comment]
Well in this specific case one of our business units wants to have exactly this functionality. They tag their files via a managed metadata column which defines the location. Then they want to search for files and then refine them to only see the files of a specific Region/area/country/location. So when they click on Region X they want to see everything below that region. Historically we used managed metadata navigation in with our on prem infrastructure but they now like the modern view and want to have the same functionality.

**Comment by phillipharding** [comment]
This is exactly what I need for an upcoming solution, where in this particular scenario, the use-case is less about search and more about navigating and exploring content by a defined hierarchy in combination with a couple of refiners

In order to do this I'm looking at having to build a custom SPA webpart, to display the hierarchy and show search results based on the term selected plus all terms below the one selected

**Comment by wobba** [comment]
UI wise you could split this into multiple refiners - one per level. I do get the ask, and idea, but some cascading dropdown filtering is imo a better user experience. I don't typically take a customer ask as being the correct ask 😉

**Comment by maru-sama** [comment]
Multiple refiners require multiple fields. The "beauty" of a managed metadata structure for the end user is that he only has to enter one value "sitecode" and gets the hierachy for free. 
The other way he either needs to enter 4 fields (in my case) or he still selects one field and I have to come up with a flow which splits this up in 4 fields afterwards.

**Comment by wobba** [comment]
@maru-sama from data input sure, from a search consumer perspective I disagree that hierarchical is good. You need to decouple data structure and filtering/searching experience. And it's ok if you disagree with my views 😁

e-commerce as a sample do have some hierarchies at times, but they also split it into multiple filters as well.

That said, we'll accept PR improvement for any refiner visualization 😋

**Comment by quarterhorse** [comment]
It's very important to retain the context of the filter which is a primary purpose of a hierarchy.  If the context can be retained and support tree selection (both whole as well as discrete elements), the UX solution doesn't need to be constrained.  It just needs to solve a business problem that, historically, hierarchies represented as trees solve particularly well.

**Comment by coupalm** [comment]
@wobba, I totally support your " I don't typically take a customer ask as being the correct ask" statement. 

For my perspective, other comments above are reflecting my needs:

- The term set hierarchy gives context. Right now I'm using the term set full path but it not a very good UX.
- As it is already hard to get people to enter metadata to content, asking people to enter multiple metadata for each level of the hierarchy would surely be not welcomed. Also it would require some kind of filtering (requiring to use PowerApps for example).

On another subject, do you know if there will be something regarding refiners with Microsoft Search soon? Honestly, I'm a little bit worried as I always prefer to use OOB component when implementing solutions for my customers. But I don't have the choice to use these "great" search components as there is no equivalent support from Microsoft since a couple of years for modern UI. I'm just starting to migrate my customers GitHub Multilingual solution to the new OOB Multilingual feature. There are good chances that I will probably need to do the same someday with search....

Until then, thanks to the modern search solution contributors for your good work!

**Comment by FranckyC** [comment]
Hi all, interesting discussions here ;). For this case, you must dissociate two things: what is a **refiner** and what is a **static filter**. 

- **Refiner**: a 'Refiner' filter means the filter gets its values from the search results and sends back the selected ones to the search WP. If the search WP has no result, there won't be any refiner values, simple as that.
- **Static filter**: a 'Static' filter means the filter doesn't care about filter values sent by the search results and provides its own arbitrary values regardless of input values. A taxonomy tree filter is typically a static filter (like a date picker for instance), meaning it doesn't care about returned refiner values. All it needs as input is the termset ID to display the terms tree. Then it sends its selected values to the search WP and doesn't use returned subsequent filters values to update its UI. 

Using a taxonomy tree filter as a refiner makes no sense and can be misleading for users because tree values would be updated every time you select something (also, the rendering logic would be a mess in this case). If you need this type of scenario (dynamically updated values), filter check boxes or a combo boxes are the best option because you keep everything flat for more readability. Most of ecommerce sites use this technique. However, I agree this is totally a valid business scenario to explore data using a hierarchical tree structure, especially when you invested in a information architecture relying on managed metadata.

What a concrete example? Here you go:

https://www.youtube.com/watch?v=udEq2n9bqlo


I know I shouldn't mention my own things here, but this example comes from the, let's say, 'Pro' version of the modern search I've released a couple of days ago. Unfortunately, I don't plan to implement it in the open source version for now. You also have the option to implement it by yourself in a forked version of the modern search if you want.

**Comment by maru-sama** [comment]
A static filter is exactly what I would need in my case, thanks for the link.

**Comment by wobba** [comment]
@maru-sama you could also build a static filter web part as a custom refiner web part - and have it work with the search result one.

**Comment by coupalm** [comment]
Hi @FranckyC, what I was looking for is, I would say, a mix of both where it would load the tree structure (using the term set ID) and then display the number of matching results for each terms (0 if no matching in search results). In this article, Elio is setting a blue color to show which terms in the hierachy have matching results. [DisplayTemplate](https://github.com/SPCSR/DisplayTemplates/tree/master/Search%20Display%20Templates/Refiners/Managed%20metadate%20refiner#optional-showing-or-hiding-terms-that-cannot-be-refined)

**Comment by FranckyC** [comment]
@coupalm to have tried to get counts or selected values for matching results in the tree like you said, I just gave up since the results weren't really statisfying and the logic quite complicated. You are trying to mix to opposite concepts together. In my opinion this is not a good idea in terms of solution design.

**Comment by coupalm** [comment]
@FranckyC, I understand. So in my case, the best option would be a static tree filter.

**Comment by FranckyC** [comment]
@coupalm yes if you want to leverage a information architecture based on taxonomy.

**Comment by maru-sama** [comment]
@FranckyC does your static filter support multi level taxanomy hierarchies as well and does it allow the usage of the # termid syntax to include all child terms as well?

**Comment by FranckyC** [comment]
@maru-sama as it not really the appropriate place to discuss about this, I invite you to contact me directly by [email](mailto:franck.cornu@aequos.ca) with your questions. I'll be happy to help. Hope you understand.

**Comment by o365guy** [comment]
Also can we have possibility to have tree view in the refinement panel webpart? esp. for the managed metadata fields
