### ISSUE TITLE
PnP Modern Search (v4) removal

### ISSUE THREAD

**Issue by danielagent** [microsoft-search/pnp-modern-search#3686]
I am new to custom web parts and recently installed the PnP Modern Search (v4) web part following the steps provided - download SFPX package, connect API's etc. It has since replaced the original OOTB Search Box webpart that was available previously.

We would like to revert back to the original state with the OOTB Search Box web part again. I have attempted to remove the PnP search web part by removing the App from the App Catalogue in SharePoint Admin center. Also remove from App Catalog Recycle Bin. I have not removed the API's prompted as part of PnP installation instructions.

I have also activated Search Server Web Parts and Templates via Site Settings, Site Collection Features.

Thanks in advance,

**Comment by kasperbolarsen** [comment]
"It has since replaced the original OOTB Search Box webpart that was available previously." : PnP Modern Search makes a small handful of web parts available in your sites. It can NOT do anything else.
However, you or somebody else might have changed Seach settings on a Site Collection in such a way that the seach query from the search box in the topbar is redirected to a specific page
![image](https://github.com/microsoft-search/pnp-modern-search/assets/20593570/a912b255-0a02-4856-9627-89fd8e7dffbd)

**Comment by danielagent** [comment]
Resolved: "Microsoft Support confirmed it was prematurely released after we reported it, but could not provide any more details.". 
@kasperbolarsen thanks for your assistance.
