### ISSUE TITLE
Error retrieving selected properties

### ISSUE THREAD

**Issue by Gbelda** [microsoft-search/pnp-modern-search#3781]
**Version used**
4.8

**Describe the bug**
I am receiving 400 Bad Request error when trying to configure the webpart selected properties dropdown.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Add pnp search results webpart to a page
2. Click Configure
3. Available data resources select Sharepoint Search
4. Click Selected properties dropdown
5. See error

**Expected behavior**
Show a list of site columns to select

**Screenshots**
![image](https://github.com/microsoft-search/pnp-modern-search/assets/87311520/fe88a3e4-da54-4def-bf61-0d7c3c88943a)

**Desktop (please complete the following information):**
 - Chrome

**Comment by kasperbolarsen** [comment]
We are not able to support old versions,  so I will suggest you install the current version,  either at tenant or site collection level,  and test if the issue remains

**Comment by syca87** [comment]
Same error - having the current version installed.

**Comment by DavorSukeri** [comment]
Same error here and also having the latest version installed (4.11.1).

What is strange is that some users don't have this issue, but some do. Happens in multiple tenants.

For example my normal account in our sandbox tenant does have this issue, but my admin account does not have.
Both of them are site col admins in that site where I have PnP Search webparts installed. Both o

**Comment by GillSpikes** [comment]
Also seeing this error/bug. I was using version 4.9.3. After updating to version 4.11.1, the error/bug remained.

**Comment by FrancoisEstrade** [comment]
Also seeing this error with 4.5.4 version. Any resolution expected soon ?

**Comment by LilianJude** [comment]
Also seeing this error with 4.11.1

**Comment by markder** [comment]
I was having this issue yesterday and earlier today, but it appears to have resolved itself.

**Comment by rockydbisogno** [comment]
I had a similar issue. I believe this due to a service outage:

Users' SharePoint Online content search results may be missing or may disappear when pages load
Users' SharePoint Online content search results may be missing or may disappear when pages load
This issue may impact the availability of some items when users perform content searches or use the News web part in SharePoint Online.
 Issue ID
SP709902
Affected services
SharePoint Online
Status
Service degradation
Start time
Jan 24, 2024, 9:21 AM PST
Issue type
Advisory

Next update
Friday, June 7, 2024 at 2:00 PM PDT

**Comment by Gbelda** [comment]
Confirming that the issue resolved itself, it is now working for me also.
