### ISSUE TITLE
Audience targeting in Verticals group lookup

### ISSUE THREAD

**Issue by claretok-hpg** [microsoft-search/pnp-modern-search#4035]
Implementing Verticals on my page and trying to add audience targeting to one of the vertical entries. When trying to select a group, I can only search and select groups from EntraID. I can't search for groups that are local to the site eg: Owners, Members, Visitors or any other custom groups.

**Comment by patrikhellgren** [comment]
That is by design as that is how out-of-the-box audience targeting works in e.g. Quick links and Navigational links.
See [Target content to a specific audience on a SharePoint site](https://support.microsoft.com/en-us/office/target-content-to-a-specific-audience-on-a-sharepoint-site-68113d1b-be99-4d4c-a61c-73b087f48a81) for more info.
