### ISSUE TITLE
Issue 2291 : same issue on last version (Items selection triggers web part refresh)

### ISSUE THREAD

**Issue by CSARTAVIQ** [microsoft-search/pnp-modern-search#4122]
Hi
I'm using the last version and I'm facing the same issue than described in 2291.
(Items selection triggers web part refresh)

Was it solved ? 

Regards

**Comment by kasperbolarsen** [comment]
Please provide a cleaned up step by step instruction that demonstrates the issue,  otherwise we will not be able to help

**Comment by CSARTAVIQ** [comment]
Hi
I have a page with a PnP Result Web Part (version 4.14.0), connected to  PnP Search WebPart and PnP Filter WebPart. It is looking for documents within a SharePoint site.
I've activated the Allow Items Selection. The Layout is Detailed List in which I've defined some columns to display (filename, title...). The purpose is to select several files to be able to use the new Download function. 
There are a lot of files meaning that I have to scroll down to see all files.
I select a first file on the page, no problem. Then I scroll down to select a second file. When I select it, the webpart automatically return to the top, meaning that the page I've just selected is no more visible. If I scroll down again, I can see the file again and if I select a third file, again the page is returning to the top. It is very not comfortable. The desired behaviour is that, if I select the page, it does not jump automatically to the top.
Note that, if I'm using the layout "List" (instead of Detailed List), I don't have this issue.
I hope it is clear.

**Comment by patrikhellgren** [comment]
This was once resolved by #3810 but I can now also reproduce this again with the latest version. I will check to see if this is a regression and get back here with the results.

**Comment by wobba** [comment]
Fixed in https://github.com/microsoft-search/pnp-modern-search/issues/4122

**Comment by lordbusiness1984** [comment]
Hi @wobba or @patrikhellgren - I followed this thread/issue and see they've been reported and resolved at least twice, but I am unfortunately still able to produce this issue with almost the exact setup as reported above by @CSARTAVIQ. I'm using 4.2.1 with a detailed search results web part also using multiselect to give users the ability download. Upon clicking any items, it is still moving the cursor to the top of the web part, which requires you to scroll back down to the now selected item and click it again. 

I am also using a handlebars expression on the filename field (Which is what I'm displaying to users) to force opening in a new window. I saw a suggestion to use a javascript handler to try to make this go away, but it doesn't seem to have any effect. 

`<a href="{{slot item @root.slots.Path}}" target="_blank" data-interception="off" onclick="event.stopPropagation();">{{Filename}}</a>`

If this is still a known issue, then I can at least tell our users its a known bug, otherwise do you have any suggestions on a workaround or fix? The only current fix is to turn off item selection completely, but users really like the ability to multiselect download. Happy to provide further information if that is helpful. Thank you!
