### ISSUE TITLE
[Question] a11y?

### ISSUE THREAD

**Issue by M365Bass** [microsoft-search/pnp-modern-search#428]
Hello,

Just wondering if the current release supports accessibility and where we can check the currently supported accessibility features (keyboard, contrast etc.)? We're keen to include modern search in our intranet but need to understand the available features (if any) around accessibility.

Thanks,
B

**Comment by wobba** [comment]
Good question and nothing we have been tracking for the OOB templates. Some of it will follow what Office UI Fabric React components have as we use them for much of the OOB templates, so that would depend on their implementation for accessibility.

As for contrast the web parts will by default use the theming of the site. For custom templates it's up to the template developer to access the theme colors using CSS (https://microsoft-search.github.io/pnp-modern-search/search-parts/templating/#work-with-sharepoint-theme).

If someone takes a stab at assessing the OOB templates for a11y we would probably incorporate needed changes.

**Comment by wobba** [comment]
Closing as we have addressed this for many of the v4 templates.
