### ISSUE TITLE
Column click sorting results only sorts page not result aset

### ISSUE THREAD

**Issue by quarterhorse** [microsoft-search/pnp-modern-search#45]
**Version used**
3.7.0.0

**Describe the bug**
In a result set, when sorting the results by clicking on a column header, it appears that only the current page of the results are sorted rather than the entire result set.  This is counter intuitive behavior and the entire result set should be sorted while the user remains on the result page.

**To Reproduce**
In an indexed site collection with content suitable for more than 1 page of results, create a site page with the search query, search results, and pagination web parts appropriately connected with a page size small enough to have multiple result pages based on content.  Sort results by title.

1 - Issue a query for *
2 - Note the first and the last entry on the page 1.
3 - Click on the title header to change sort order.  Note the original sort last entry on the page is now the first and the first original sort is now the last entry.
3 - Click to page two and repeat the click sort noticing that page and only that page are sorted.

**Expected behavior**
The entire result set, rather than the current page, should be sorted with the user left on the original result set page.

**Comment by FranckyC** [comment]
@quarterhorse, I guess you are talking about the 'Details list' layout. The sort feature here is only "client-side" and has nothing to do with the search here and this is the expected behavior. If you need to sort results dynamically, you can still use the 'Sortable properties' option in the property pane:

![image](https://user-images.githubusercontent.com/5659122/72226534-17c2db00-3560-11ea-9c93-c3322e472bb5.png)
