### ISSUE TITLE
Remove duplicates toggle option

### ISSUE THREAD

**Issue by vtikam** [microsoft-search/pnp-modern-search#477]
**Is your feature request related to a problem? Please describe.**
In the classic sharepoint webpart, there is an option available in query builder to remove duplicate search results. We select this, the duplicate entries are not shown in search results.
![image](https://user-images.githubusercontent.com/14929827/93477281-783cc000-f918-11ea-96a9-83889d9e9315.png)

I could not find similar option in pnp modern search results webpart

**Describe the solution you'd like**
Can we have similar toggle /configuration in pnp modern search webpart

**Comment by wobba** [comment]
By default we don't remove duplicates as the feature is to put it honest, crap. Due to the fuzzy technical implementation too many results are filtered out. I'm not too keen on adding a toggle for this. You should be able to work around it possibly by creating a result source which has the setting and use that in your configuration.
