### ISSUE TITLE
Connect to External API and display results in Search Results

### ISSUE THREAD

**Issue by Rbob3267** [microsoft-search/pnp-modern-search#538]
We have a requirement to connect to external API's. When user enter any keyword, results are displaying from SharePoint results source ID. Also at same time we need to connect with externals APIs and get the result and display it in Results table.

Is is possible to display results in SharePoint Online using pnp-modern-search solution?

Thanks in Advance!

**Comment by FranckyC** [comment]
Hi @meherkanth, the current PnP modern search solution only targets SharePoint search API for now. In the future, we will add Microsoft Search API where you could index content from external source via custom connectors (see https://docs.microsoft.com/en-us/graph/search-concept-overview). Otherwise, depending of your API type, you should look for commercial solutions similar to modern search.
