### ISSUE TITLE
Results Webpart return extraneous items when using a custom "Results Source Id /Name" 

### ISSUE THREAD

**Issue by donshults** [microsoft-search/pnp-modern-search#549]
**Version used**
pnp-modern-search-parts 3.15.3.0

**Describe the bug**
Using the Search Results Web part and custom Search Result Sources return extraneous items in the result set.
I have the Results Webpart set to return only .png & .gif files in the current site collection. (I expect 10 items to be returned)
In my testing, 5301 items were returned.
The extraneous items (beyond the targeted 10) returned include items from:
GeoLocated Data Centers:    https://{tenant}grb.sharepoint.com, https://{tenant}jpn.sharepoint.com ...
OneDrive Locations of the Logged in user:  https://{tenant}-my.sharepoint.com/personal/{user_name}{tenant}_com/

**To Reproduce**
1. Go to 'Site Setting | Site Collection Administration'
2. Click on 'Search Result Sources'
3. Create a New Result Source for the Site Collection
4. Launch the query builder and enter the following Query Text:` {searchTerms}  Path:{SiteCollection.URL} (SecondaryFileExtension:gif OR  SecondaryFileExtension:png)`. Test the Query to insure it returns the expected results.
5. Select the new Result Source, and copy the sourceId from the URL to be used in the "Results Web part".
6. Press OK and return to the Site Page that uses the "Results Web part"
7. Edit the Results Web part properties, on page 2 update the "Result Source Id / Name" property with the sourceId that you copies from step 5. Save the properties and the page.
8. Test your query again and review the results.

**Expected behavior**
**The results set returned by a wild card search should be the same results set returned by the Query Builder Test.
In this test that should only have been about 7 items.**
In my testing, the Query Builder returned 7 items.
In my testing of the Classic Results Web part return 7 items.
In my testing, the New Results web part using a query of `"*"` and the newly created Results Source 5298 items.
In my testing, the New Results web part using a query of `"*"` with the custom Results set removed return 3635012 items.

**Desktop Windows 10 Enterprise:**
 - Browser Edge 86.0.622.63 

**Other Context
It appears that that Site Collection Result set is returning the expected results. 
Using that Result Set in the new Results Web part seems to allow some extraneous content from OneDrive and GeoLocated content in other data centers. Our primary data center is North America. 
It does appear to limit the return of items from local SharePoint in the North America region.

_This image compares the Classic and Modern Search Webparts in the same Site Collection using the same Results Set. Notice the difference in the item count._
![SearchCompare1](https://user-images.githubusercontent.com/4684182/98879333-2442e900-243a-11eb-8feb-dd2f96b9f838.png)

**Comment by wobba** [comment]
Can you switch to the debug template and look at the QueryModification output? By default we do include multi-geo, but your path filter should exclude them. Can you also verify the query being sent is looking equal to that for classic/query builder?

**Comment by donshults** [comment]
Hi Mikael,

I’ve looked at the output, but I’m not sure I know what I’m looking for. I’ve attached the information in the Query.json file.

As I said in my issue, the Site Collection Level Results Set is the same for both my classic page and the modern page.
I’ve attached and image of it’s configuration as well.

Let me know what you think.

Don Shults

**Comment by donshults** [comment]
Mikael,
Stumbled on a possible solution.
I've got both the Classic & Modern Web parts showing the same results. See Image:
![MSTroubleShoot2](https://user-images.githubusercontent.com/4684182/98966596-5139df00-24c0-11eb-9865-92518092229a.png)

The solution seems to have been to remove the Default Value from the Query Template on page 2 of the properties pane.
The default value seems to have been "Search query in KQL Format" (which I thought was a placeholder hint).
By replacing this value with a blank space, the Result Source Id / Name seems to be in effect.
![MSTroubleShoot1](https://user-images.githubusercontent.com/4684182/98967254-2439fc00-24c1-11eb-895f-87ce96067362.png)

Not sure how or what the Query Template field on page 2 of the property pane is supposed to contain. And how it affects the overall query. But it's clear, that the default value should not be used if you are using a Result Source Id / Name.
Let me know if you can confirm this is a valid solution and not just a minor workaround.

Thanks

**Comment by wobba** [comment]
Put {searchTerms} in the template.

**Comment by donshults** [comment]
Putting {searchTerms} in the Query Template field results 5300 results instead of 7. It's effectively the same as my example where the Query Template is set to the default value, 'Search query in KQL format'.

**Comment by wobba** [comment]
Can you use the result source name/id? And just {searchTerms} in the template. That should allow you to use the result source's template.

**Comment by donshults** [comment]
> Can you use the result source name/id? And just {searchTerms} in the template. That should allow you to use the result source's template.

No.  When I edit the Resource Source added to the Site Collection Setting area, I get about 8 results. This appears to be correct.
Using the Result Source ID with **just** the {searchTerms} results in 5302 results.
![MSTroubleShoot5](https://user-images.githubusercontent.com/4684182/99268458-0975c900-27da-11eb-9d3a-a19282289921.png)

**Comment by wobba** [comment]
I think I have repro and could be a bug. I'll investigate a bit and report back.

**Comment by wobba** [comment]
A workaround is to use the name instead of the id. For a site scoped results source `SPSite|<name>`

**Comment by wobba** [comment]
Once I used the name, then the id, then the id worked. Weird. Could be caching issue of sorts.

**Comment by donshults** [comment]
Sorry Guys, tried both of those solutions, but I'm not able to get to the correct result. In order to get the webpart to limit to the site collection, I must still add the 'Path:' statement to the Query Template in the Results Webpart Properties.

**Comment by wobba** [comment]
@donshults thinking this is could be geo related somehow. I'll try to set up a test in the Microsoft tenant.

Can you try in the SharePoint Query Tool to connect to your site collection, and add this to enable multi-geo:

![image](https://user-images.githubusercontent.com/51104/99648714-a2fbdf80-2a53-11eb-8a2d-99c4ab8e4407.png)

And enter the result source id as well - or try with the `SPSite|Name` notation.

![image](https://user-images.githubusercontent.com/51104/99648790-b7d87300-2a53-11eb-95f1-75b72210a0d1.png)

**Comment by wobba** [comment]
Can you paste in a copy of the request JSON and response JSON? Just remove any PII, and remove the result collection of items.

**Comment by donshults** [comment]
Security issues on site prevent me from using the SharePoint Query Tool at the moment.

**Comment by wobba** [comment]
@donshults Hit `F12` in your browser and filter on `postquery` in the network tab.

**Comment by donshults** [comment]
> @donshults Hit `F12` in your browser and filter on `postquery` in the network tab.

Noting is filtered using postquery. 

![image](https://user-images.githubusercontent.com/4684182/102244557-4dc7b800-3eb1-11eb-9c90-968e4e9ec54f.png)

**Comment by wobba** [comment]
You should see something like this when you click "search". That's the endpoint PnP is hitting :)

![image](https://user-images.githubusercontent.com/51104/102264881-8c438e00-3f16-11eb-913b-ee08e262779d.png)

**Comment by chntn** [comment]
Hello @wobba I getting same unexcepted result count as @donshults getting but I am searching by Value and Property from specific list items (list have 19 items).
Could you check what is the issue?

**Version used**
pnp-modern-search-parts 3.12.1.0

**Describe the bug**
Using the Search Results Web part and custom Search Result Sources return extraneous items in the result set when I search by managed property with wrong value (expected date format) eg. [RefinableDateSingle00 = "12"] or [RefinableDateSingle00 = "any text"].
I have used existing Managed property of site to find the results.
I have the Results Webpart set to return only specific list items in the current site collection. (I expect no result found to be returned or any result)
In my testing, 62054097 items were returned.

The extraneous items (beyond the targeted 19) returned include items from:
GeoLocated Data Centers: https://{tenant}grb.sharepoint.com, https://{tenant}jpn.sharepoint.com ...
OneDrive Locations of the Logged in user: https://{tenant}-my.sharepoint.com/personal/{user_name}{tenant}_com/
Other Microsoft SharePoint site with their Manged Property values

**To Reproduce**
Steps to reproduce the behaviour: which are almost same as @donshults mention.
1. Go to 'Site Setting | Site Collection Administration'
2. Click on 'Search Result Sources'
3. Create a New Result Source for the Site Collection
4. Launch the query builder and enter the following Query Text: {searchTerms} Path:{LIST.URL}. Test the Query to insure it returns the expected results. and have test with {searchTerms} and Result Source in the template
5. Select the new Result Source, and copy the sourceId from the URL to be used in the "Results Web part".
6. Press OK and return to the Site Page that uses the "Results Web part"
7. Edit the Results Web part properties, on page 2 update the "Result Source Id / Name" property with the sourceId that you copies from step 5. Save the properties and the page.
8. Test your query again and review the results.


**Expected behavior**
**The results set returned by a Manged Property search should be return no result.
In this test that should only have been about 19 items form provide list.**
In my testing, the Query Builder returned 19 items using "*" on load.
In my testing, the New Results web part using a query of "RefinableDateSingle00 = "12"" and the newly created Results Source 62054097 items.
In my testing, the New Results web part using a query of "RefinableDateSingle00 = "12"" and it getting other site Managed Property value in results , like RefinableString00 have mapped with Industry value in my site, It should return Industry value but it return other site RefinableString00 mapped value, either it should not return on others site results or should not return their site Managed Property.


**Screenshots**
If applicable, add screenshots to help explain your problem.
Result Source Config
![BuildQuery](https://user-images.githubusercontent.com/4496711/104739770-22b0dc80-576d-11eb-9708-15d4e0ab2765.png)

Modern Search Result WebPart
![ResultsCount](https://user-images.githubusercontent.com/4496711/104740013-6e638600-576d-11eb-981f-53e724c34acf.png)

** #request JSON**

:authority: microsoftapc.sharepoint.com
:method: POST
:path: /teams/{SiteName}/_api/search/postquery
:scheme: https
accept: application/json; odata=minimalmetadata
accept-encoding: gzip, deflate, br
accept-language: en-GB,en;q=0.9,en-US;q=0.8,hi;q=0.7
cache-control: max-age=0
content-length: 1499
content-type: application/json;odata=verbose;charset=utf-8
cookie: SearchSession=73e59dea%2D5d3b%2D4d7c%2D84dd%2D508c96edfb54; MicrosoftApplicationsTelemetryDeviceId=827319d1-3169-4cea-ac8b-a90dd207e12a; MicrosoftApplicationsTelemetryFirstLaunchTime=2021-01-15T07:52:52.410Z; WSS_FullScreenMode=false; PowerPointWacDataCenter=SG1; WacDataCenter=SG1; ec63b09b974847ba9018beeadd40520473cda308da67454da3b6beab84bdc7eci%3A0%23%2Ef%7Cmembership%7Cv%2Dmahfa%40microsoft%2Ecom=0; rtFa=GmbWFd+B04n6JMQITcK6B+P/s/K4lIipX/7Lk7UpDUEmRUM2M0IwOUItOTc0OC00N0JBLTkwMTgtQkVFQURENDA1MjA0q3noCjlY+ysDk8ywF4H5Z5i1YCYNSI/LicFHIevJyZW4i4zWKomVdCdM4NXgAtAWMV/S8EkNpUhc8U/awpr0ibR9W+JDqMUDVk693UeuoiU5+ZxjeBhw0n+ge5jAH1wygr3QatBOzfviQdPb+IkqMfi/6yrI3jM5ENn3P/WbEomKRix/mUAbbYR1mhnMLip8gQrYc6gYKZEEQyZOYslqiA4VW5/LghJjbbfhxDv/eqAMUj3zAQ7yW1kuXGT2QF0MDsiMEdUpMJIcZwmpxwnGEsF6Ogf2G+zSmPTgDXHFE7Z4HWqpwckzoAB74xKHtd+/+sx5ksOtNA0mR1vBQFHIIEUAAAA=; FedAuth=77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48U1A+VjgsMGguZnxtZW1iZXJzaGlwfDEwMDMyMDAwNGRjMWMxMGRAbGl2ZS5jb20sMCMuZnxtZW1iZXJzaGlwfHYtbWFoZmFAbWljcm9zb2Z0LmNvbSwxMzI1MzcyMTMxMDAwMDAwMDAsMTMyMjk1MzI0NDUwMDAwMDAwLDEzMjU1NjEyNDY5NjYzNTM2OCwyMDMuMTA5Ljg3LjIzNiwxOTUsZWM2M2IwOWItOTc0OC00N2JhLTkwMTgtYmVlYWRkNDA1MjA0LCw2ZTcwOWQ0NC1mNzUyLTQ3YzQtODczZi1iZTBiZGU4ZmQwOWEsZTVlMjk3YzItNjZjYS00ZGNhLTkwZjItM2M0NjAwNTA1NThmLGU1ZTI5N2MyLTY2Y2EtNGRjYS05MGYyLTNjNDYwMDUwNTU4ZiwsMCwxMzI1NTI2Njg2OTU4NTQwOTksMTMyNTU0Mzk2Njk1ODU0MDk5LCwsZXlKNGJYTmZZMk1pT2lKYlhDSkRVREZjSWwwaUxDSjRiWE5mYzNOdElqb2lNU0o5LDI2NTA0Njc3NDM5OTk5OTk5OTksMTMyNTUxODA0NjkwMDAwMDAwLDdhZjc5ZTk2LWMzNTUtNDM1Yy1iMDUxLTQ3MzhjOTIwMzZlYSxOUlRVVS9rQmw1dG5zczJvTVZHVUFCaVJzUlo1Lys5S0x0SnpnQmo5Z0R2dHIyOU5YNGY1NXNhM0pRcEliL2ovSWdOeTI3SjNhdzNDNGlQbXBhV0Z2MnA2Q2cxZ0JuZ291YkVPSE5ScDJ3S0hZKzlHL2dpblZTMHYwMFlNMjhZTEpVV3FUUEErRjNSUFJLQ0xON2czSTE2SUZLLzhFd3J6dTBUeVBWM1Vqays0V0R1aVRUbHN5L3Z0WmNFNS82Z2xyWUUwVXhWL2Yzek4zRUU3aWV1elNtZTlGbllrSXFrRGZPSlk2eUtmejdNcHVnaUl0cTNqSmZNMjVUQmo4R1lUVEZGSFRTNEpkdDQzTUxYVkFKTmZTTVlLU2NrYVNtSnBFbjAwOTF6aVNXRUJHa3d5ZGphT3JhZVdpeHY4KzR3Z1BXa2RVTjVMeStjbnQvZ2RLU2laaEE9PTwvU1A+; SPWorkLoadAttribution=Url=https://microsoftapc.sharepoint.com/teams/{SiteName}/lists/{ListName}/allitems.aspx&AppTitle=ClassicDocLibListPage
origin: https://microsoftapc.sharepoint.com
referer: https://microsoftapc.sharepoint.com/teams/{SiteName}/SitePages/{Page.aspx}
sec-ch-ua: "Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"
sec-ch-ua-mobile: ?0
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
x-clientservice-clienttag: 810515e5-4b12-4d56-a49f-bc7880b9a99e:1.0.0.0, <AppID>:1.0.0.0
x-clienttag: NONISV|Microsoft|<AppID>/1.0.0.0, NONISV|Microsoft|<AppID>/1.0.0.0
x-pnpjs-tracking: se.execute
x-requestdigest: 0xAE15D7DB6621347C3558AC99D7361E7203D09419F7B98A76BA13D460DAA49493C340E90C0CE41718692776DA03C793E21129AC94464EE2FDD69B694BB0440197,15 Jan 2021 14:08:28 -0000

**request Payload**

{request: {__metadata: {type: "Microsoft.Office.Server.Search.REST.SearchRequest"},…}}
request: {__metadata: {type: "Microsoft.Office.Server.Search.REST.SearchRequest"},…}
ClientType: "810515e5-4b12-4d56-a49f-bc7880b9a99e"
HitHighlightedProperties: {results: []}
results: []
Properties: {results: [{Name: "EnableDynamicGroups", Value: {BoolVal: true, QueryPropertyValueTypeIndex: 3}},…]}
QueryTemplate: "{searchTerms} Path:https://microsoftapc.sharepoint.com/teams/{SiteName}/Lists/{LisName}"
Querytext: "RefinableDateSingle00  = "12""
RefinementFilters: {results: ["Title:not("[LisName]")"]}
results: ["Title:not("[LisName]")"]
Refiners: "RefinableString00,RefinableString02,RefinableString03,RefinableString01,RefinableDateSingle00(discretize=manual/2020-01-15T14:08:57.863Z/2020-10-15T14:08:57.863Z/2020-12-15T14:08:57.863Z/2021-01-08T14:08:57.863Z/2021-01-14T14:08:57.863Z)"
ReorderingRules: {results: []}
results: []
RowLimit: "9"
SelectProperties: {,…}
results: ["Title", "Path", "ListItemID", "RefinableString04", "RefinableString05", "RefinableString06",…]
SortList: {results: [{Property: "RefinableDateSingle00", Direction: 1}]}
results: [{Property: "RefinableDateSingle00", Direction: 1}]
0: {Property: "RefinableDateSingle00", Direction: 1}
StartRow: 0
TrimDuplicates: false
__metadata: {type: "Microsoft.Office.Server.Search.REST.SearchRequest"}
type: "Microsoft.Office.Server.Search.REST.SearchRequest"

**Response** 
![Response](https://user-images.githubusercontent.com/4496711/104743360-9fde5080-5771-11eb-814d-f3be2599edc9.png)


**Desktop Windows 10 Pro**
 - Browser : Google Chrome Version 87.0.4280.141 (Official Build) (64-bit)

**Comment by wobba** [comment]
@chntn is your questions about extra items when you pass in a "wrong" value to a RefinableDate property? If so, that's not a web part issue, but how KQL is parsed and handled behind the scenes. Just make sure you don't pass data not matching whay you query for.

Also, property queries should *not* have spaces between the property, operator and value.

`RefinableDateSingle00 = "12"` <- wrong, handled as 3 terms
`RefinableDateSingle00="12"` <- correct property query

**Comment by chntn** [comment]
Thank you @wobba for your response.

I have tried with without space and other workaround but no luck still getting same error. Please see the captured screenshot.
![ResultsCount_updated](https://user-images.githubusercontent.com/4496711/105142083-22736100-5b20-11eb-862e-0633c4e3cc64.png)

**Comment by wobba** [comment]
Well, the query is "wrong", as you're not passing in a date. It's an API issue, not web part related.
