### ISSUE TITLE
Call Search Service from library component

### ISSUE THREAD

**Issue by Bhargavikandru** [microsoft-search/pnp-modern-search#56]
**Is your feature request related to a problem? Please describe.**
I need an alphabetical filter in the results part. 
I have added alphabetical filter in library component, On clicking on any alphabet do a search call with existing query keywords and refiners and then render all web parts with the output data.

**Comment by FranckyC** [comment]
Hi @Bhargavikandru not sure what you are talking about. There is already a sort control in the search results Web Part. Please provide more context.

**Comment by Bhargavikandru** [comment]
I need Filtering of results.
![image](https://user-images.githubusercontent.com/43135174/72957487-c3bebe80-3dc9-11ea-9a59-c8bc69767dbd.png)
I have added alphabets and on clicking on the alphabet, the results should display only starting with that alphabet.
I have added this in library component. how to do search call and get the filtered results on clicking any alphabet.

**Comment by FranckyC** [comment]
Hi  @Bhargavikandru , there is no direct way to send the info to the search results WP from a library component (programmatically I mean). However, you could use the URL hash or a query parameter as an intermediary. Then configure the search WP to use this value from the dynamic data source 'Page environment'. Hope it helps.

**Comment by Bhargavikandru** [comment]
Hi @FranckyC, I didn't get you what are you saying.
Can you provide it in more informative.

**Comment by FranckyC** [comment]
@Bhargavikandru In the extensibility library you can't submit a query directly by code to the connected search results WP. You have to use other techniques for that. Using the hash parameter from URL `#` or a query string parameter are possible solutions to pass the selected alphabet letter to this Web Part and make the call since it supports special tokens `{Querystring.<param>` in the query template. Is it more clear?

**Comment by wobba** [comment]
Closing as inactive.
