### ISSUE TITLE
How to include new Library fields in the result

### ISSUE THREAD

**Issue by MartinDrenth** [microsoft-search/pnp-modern-search#578]
Hi There
Great product! 
I have a (calculated) field added to a DocLibrary, but I cannot find it in the 'Selected properties' or in the 'Edit layout slots for this data source'. How can I have that field included in the result, so I can show it and refine the search on that field? It is a Date-field.

Tnx
Martin

**Comment by FranckyC** [comment]
Hi @MartinDrenth, the selected properties dropdown does not show custom managed properties. You have to type your value directly to add it to the collection. Then, if present in the results you will be able to use it in the slots.

**Comment by MartinDrenth** [comment]
Hy @FranckyC. Thanks for your quick reply! What puzzles me is that another field that I added (it is called Datum Offerte, and easily recognizable, because it is spelled in dutch) _does_ show up in the selected properties. Why does the other field (called 'CalcDate', type date, calculated) _does not_ show up?
How and where do I manually add a field to the collection?

**Comment by wobba** [comment]
From your description you added a field to a library and expect it to automagically show up as a property? That doesn't work. You need to map the corresponding crawled property for the field to a managed property.

If you want it refinable, map it for example `RefinableDate00`.

Also, you can put the cursor in the field and just type a valid managed property name and it will be used.

**Comment by FranckyC** [comment]
@MartinDrenth does this explanation resolve your issue?

**Comment by MartinDrenth** [comment]
Hi Franck
Thanks for asking! I was a little demotivated by Mikael's answer 😓. There were so many terms in it that I didn't know that I couldn't complete the puzzle. I've never been into SharePoint's Search Configuration, so everything is new to me. But I tried again and found out how to map a crawled property to a managed property, as shown in this picture:
[cid:image002.png@01D6D243.15C0B180]

So the crawled property named ‘ows_flo_OffertedatumCalc’ is now mapped to RefinableDate00. But from here I’m stuck again. This ‘RefinableDate00’ field seems not to pop up anywhere in the PnP – Search Results configuration or in the PnP – Search Filters yet. I have no clue yet what to do. This field is a calculated column that converts the ‘Datum Offerte’ (=Offer date) that Syntex picked up to an actual Date. That date I want to use in the refinement filter, as you might expect.

Help would be highly appreciated.

Martin

**Comment by wobba** [comment]
@MartinDrenth As long as you have modified/recrawled content after your mapping, `RefinableDate00` should be populated. If it doesn't list, then type it in manually. Going from SharePoint column to search takes some time to learn, and reading the documentation out there will put you on the right track. Also many blog posts covering the topic. And the concept hasn't change since SP2013 :)

https://docs.microsoft.com/en-us/sharepoint/manage-search-schema

A better place to ask search config questions (because we don't have the bandwidth here) is https://techcommunity.microsoft.com/t5/sharepoint/bd-p/SharePoint_General or https://techcommunity.microsoft.com/t5/microsoft-search/bd-p/MicrosoftSearch
