### ISSUE TITLE
refinabledecimal/number does not appear to work again

### ISSUE THREAD

**Issue by cpluceDev** [microsoft-search/pnp-modern-search#591]
i just downloaded the latest version because we needed a fix for when the search web part conflicts with the OOTB search but now it appears that this issue is back

https://github.com/microsoft-search/pnp-modern-search/issues/498

Can someone test

**Comment by wobba** [comment]
Can you please not delete the bug template. "Latest version" is very hard to decipher as we have a latest v4-preview and a latest v3 which is v3.16.

**Comment by wobba** [comment]
Tried with v3.16 and seems to work just fine. Please

![image](https://user-images.githubusercontent.com/51104/101048535-fd805a00-3582-11eb-94f5-7f541d245771.png)

Tried with v4
![image](https://user-images.githubusercontent.com/51104/101048800-3a4c5100-3583-11eb-8b12-33dbdf8bfc27.png)

**Comment by cpluceDev** [comment]
sorry about that. i have v3.16. I wont do preview in prod. maybe it didnt take the update even though it shows 3.16 thanks

**Comment by cpluceDev** [comment]
"Can you please not delete the bug template. " - What do you mean? thx

**Comment by wobba** [comment]
When you click new issue/bug there are headers and info to fill out, which you just clear out.


!! Check existing issues before logging new ones !!

**Version used**
Ex: 3.13

**Describe the bug**
A clear and concise description of what the bug is. Keep questions and bugs related to the web parts. If the issue relates to KQL or question around crawled and managed properties please use [Microsoft TechCommunity](https://techcommunity.microsoft.com/t5/sharepoint-developer/bd-p/SharePointDev). Which means, if you experience the same behavior in classic web parts, then it's not an issue with PnP Modern Search 😉

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]

**Additional context**
Add any other context about the problem here.

**Comment by wobba** [comment]
And I cannot repro your issue with 3.16. Make sure it's properly updated.
