### ISSUE TITLE
Empty Data Result in SharePoint Mobile App about PnP Search Web Part

### ISSUE THREAD

**Issue by garywky** [microsoft-search/pnp-modern-search#639]
**Version used**
4.0.0.0

**Describe the bug**
Empty Data Result in SharePoint Mobile App about PnP Search Web Part, the result display well on desktop and mobile web browser.

**Expected behavior**
Display the filter and result

**Screenshots**
![file](https://user-images.githubusercontent.com/76786461/103368237-07ee2f00-4b02-11eb-9f2f-2b8ba9d3ee96.jpeg)

**Desktop (please complete the following information):**
 - iOS SharePoint App v4.27.1 and Android SharePoint App v3.23.0

**Comment by wobba** [comment]
Which data provider do you use, and is it showing blank for all setups?

**Comment by Laul0** [comment]
The issue was reproduced on iOS and SharePoint App 4.33.1 and Edge for iOS.

![IMG_C666F3961D11-1](https://user-images.githubusercontent.com/15279205/122120530-890f5900-cdf8-11eb-9b63-5b4f96d760c5.jpeg)

Page configuration:
- Search box
- Vertical
- Search result based on SharePoint Search

I will spend more investigating time next days

**Comment by wobba** [comment]
@Laul0 Can verify that the dev branch work fine in the SharePoint iOS mobile app. Which means the upcoming v4.3 seems to work fine. Closing for now.
