### ISSUE TITLE
V4 Search KQL token translation

### ISSUE THREAD

**Issue by BBokdam** [microsoft-search/pnp-modern-search#656]
**Version used**
Version 4.0.0

**Describe the bug**
This bug is related to the KQL. I use a token in the query and is converted correctly. The token I use is {|ManagedProperty:{Page.<ColumnName>.TermID}}. The column is a managed metadata column with multiple values. The values are converted correctly and are shown in the "queryModification". (Screenshot) 

The problem is the syntax. The OR is missing in the query. 
((refinablestring05:\"10660250-3e41-469d-8d81-1787b6d0e3f0 02fda817-ebe3-4a0c-aba2-0958d79294d2 43fe9538-9f93-48f4-9c46-366f5a9cddcb\")) 

This should be:
((Refinablestring05:#010660250-3e41-469d-8d81-1787b6d0e3f0) OR (Refinablestring05:#002fda817-ebe3-4a0c-aba2-0958d79294d2) OR (Refinablestring05:#043fe9538-9f93-48f4-9c46-366f5a9cddcb))

**To Reproduce**
1. Create a column on a SitePage library. Type: Managed Metadata, multi value
2.Create a Managed property from that column (in my case refinablestring05)
3.Use the search results webpart with the above query to get the results
4. See the about without the OR function

**Expected behavior**
The problem is the syntax. The OR is missing in the query. 
((refinablestring05:\"10660250-3e41-469d-8d81-1787b6d0e3f0 02fda817-ebe3-4a0c-aba2-0958d79294d2 43fe9538-9f93-48f4-9c46-366f5a9cddcb\")) 

This should be:
((Refinablestring05:#010660250-3e41-469d-8d81-1787b6d0e3f0) OR (Refinablestring05:#002fda817-ebe3-4a0c-aba2-0958d79294d2) OR (Refinablestring05:#043fe9538-9f93-48f4-9c46-366f5a9cddcb))

**Screenshots**
![screenshotSearchRestults](https://user-images.githubusercontent.com/22632809/104324049-321ef400-54e7-11eb-823e-4f42a728aaad.png)
![appcatalog](https://user-images.githubusercontent.com/22632809/104324233-77dbbc80-54e7-11eb-8f73-e76e648641f1.png)

**Desktop (please complete the following information):**
 - Windows 10 build 20H2
 - Edge 87.0.664.75 
 - SharePoint Online
 - Pnp-Modern Search webpart 4.0.0 (Screenshot)

**Comment by wobba** [comment]
We haven't added support for the `{|` notation and is why you are seeing this.

**Comment by robegoja** [comment]
I just wanted to add some information it seems the logic is using a comma for the breaking of the token into the multiple values. 
I dont have the development experience to fix or provide the update but I found that there is a comment at that line stating its for the multivalue metadata column and the multivalue choice fields.  I have both mapped to crawled properties and the following shows the values that come back:

"owstaxidmetadataalltagsinfo": "L0|#0f05afd07-d1ae-4489-bea7-175d259bb244|Cash Management;L0|#0e8266911-d05c-44a7-9571-1d7ffa15597c|Commercial Banking"

**Mapped property RefinableString100 - crawled metadata column**
       "RefinableString100": "Cash Management;Commercial Banking;GP0|#f05afd07-d1ae-4489-bea7-175d259bb244;L0|#0f05afd07-d1ae-4489-bea7-175d259bb244|Cash Management;GTSet|#da0bcb81-9e67-47c0-9ed9-52bbc4e443a1;GP0|#e8266911-d05c-44a7-9571-1d7ffa15597c;L0|#0e8266911-d05c-44a7-9571-1d7ffa15597c|Commercial Banking"
 
**Mapped property RefinableString101 - crawled site column**
        "RefinableString101": "Cash Management;#Commercial Banking;#"

The values are separated by a semicolon instead of a comma.

**Comment by FranckyC** [comment]
Hi @BBokdam, this should be resolved in the develop branch.
