### ISSUE TITLE
Preview without toolbar

### ISSUE THREAD

**Issue by schoier** [microsoft-search/pnp-modern-search#764]
**Version used**
4.0.0

**Describe the bug**
With the new version all previews have a complete toolbar. That makes it hard to get a good overview of the document.
![image](https://user-images.githubusercontent.com/33417064/107516623-f68e4d00-6bac-11eb-82f7-bfd448ac9173.png)

In the old version the previews didn't have any toolbar (at least not when using "{{getPreviewSrc item}}" in the template).
![image](https://user-images.githubusercontent.com/33417064/107516637-fd1cc480-6bac-11eb-8809-746af571cd3b.png)

Is there any easy way to change this, another slot value etc?

**Desktop (please complete the following information):**
 - Edge

**Comment by wobba** [comment]
We simplified the code to use the same pattern for all files, and SharePoint redirects to the edit experience when appending "?web=1". We have a couple of options:
* Re-add logic to use interactive preview for Word/Excel/PowerPoint
* Show a one page thumbnail instead

**Comment by jensotto** [comment]
I think the preview should be a preview ie. view only, and not edit mode as it is now. You can end up having users do unforseen edits, and we have seen that edits are sometimes not saved adding another level of confusion and unreliabaility. Also all the menu items clutter the visible area for the document.

**Comment by wobba** [comment]
Personally I'd rather remove the onhover larger view. If you want to view the doc or interact with it, then open it.

I know some people enjoy the feature and we have gotten feedback in Microsoft Search after we removed it from the OOB UX - but not a lot of it. And we haven't seen any movement in search success after removing it. It is better replaced with a better component, which don't exist.

@schoier what's your take if we remove it instead of changing it?

**Comment by schoier** [comment]
@wobba I usually use the pnp search in bigger search solutions, like archives. In these cases the preview is a very helpful feature. I agree that the preview isn´t good if you want to interact with or edit the document, but to get a preview of the document to make sure it is the right one before you open the file.

**Comment by wobba** [comment]
I think if we change to the logic used in v3 `getUrl` that should fix this. There are scenarios where this logic fails, but probably something to live with.

**Comment by jamesdellowE2** [comment]
Removing _?web=1_ so it is just a static preview rather than an interactive preview would be an improvement to avoid unintended edits etc. But the overall user experience isn't great even when you do that - there is a lot of wasted space at the top of the preview (the controls are quite greedy in the layout).

![image](https://user-images.githubusercontent.com/87298339/125244805-19c35100-e333-11eb-8f5d-353cfaec6cfb.png)

Do you have any control over the orientation of the preview - e.g. make it display vertically along the longest edge rather than horizontally?

An option to have a 1-page thumbnail could be useful.

**Comment by wobba** [comment]
If we can figure out parameters maybe we can control width etc, but I'm unaware of this right now. Thumbnail image is doable, and is what the result uses on page. You can also question what the value of an interactive preview in a smaller frame actually will accomplish for the end-user.

**Comment by wobba** [comment]
Fixed in the next version.
