### ISSUE TITLE
V3.16 - Sort order doesn't work

### ISSUE THREAD

**Issue by mark-ferkaluk** [microsoft-search/pnp-modern-search#768]
Hi guys,

I am having trouble to configure the sort order for my query. What I did:

- I have two lists where Hyperlinks are saved (personal and global). Those lists have two different content types
- I configured the search result webpart, to display only those two content types and also only the personal links that were created by {me}. Which works totally fine.
- In both lists is a number field, so users can define a sort order within the list (both fields have the same name and using the same crawled property)
- I used a RefinableInt and a RefineableString and configured them to use the appropriate crawled property of the sort order fields.
- Now I configured in the sort order of the result webpart  to sort for the RefinableInt value (also tried RefineableString). But it doesn't work. The values in the sort order fields are just from 1 to 10.

I am using a details list template to render the items, that only contains 1 column with a handlebar expression. I DON'T want the user to be able to sort the list. Should be done by the query.

To be mentioned: I have paging activated. 5 items per page. Would be cool to have the sort order working over all pages, not only for the 5 that are displayed.

Can you help me?

Best regards,

Mark

**Comment by wobba** [comment]
Issue don't follow the bug template. Please re-log using the full template, include screenshots of setup, and it's not clear how pagination is related, as you seem to say it works on page 1, but in the overall you say it's not working at all.

Also, you should validate a working repro using the SharePoint Search Query Tool or classic web parts, so that we can see if it's API related or web part related.
