### ISSUE TITLE
PnP Modern Search's Managed Property Content/Description Field Not Displaying in Profile Card View

### ISSUE THREAD

**Issue by hduongGW** [microsoft-search/pnp-modern-search#997]
I am having trouble rendering the description/content managed property named RefinableString02 in the pnp-modern-search's Search-Parts web part.

My solution was to add a custom web component below and adding it to the handlebar edit code section in the UI, but the description/contents still is not showing.

<document-card-content-component
data-description="{ {RefinableString02}}"
data-content-string-param="Test value"
data-content-object-param="{ {JSONstringify this 2}}"

</document-card-content-component>
Reference used: https://github.com/microsoft-search/pnp-modern-search/blob/main/docs/extensibility/custom_web_component.md

Other solutions are appreciated.

**Comment by wobba** [comment]
Use the debug rendering template to ensure you have added RefinableString02 to the list of managed properties to be fetched.

**Comment by hduongGW** [comment]
It is not in there and it has been properly mapped.  My question is, how do I get my component's data-description {{RefinableString02}} to be in there /render in the UI?

**Comment by wobba** [comment]
For v4 look at selected properties section https://microsoft-search.github.io/pnp-modern-search/usage/search-results/data-sources/#sharepoint-search For v3, the same https://microsoft-search.github.io/pnp-modern-search/v3/search-parts/search-results/#search-settings 

Which is why we have an issue template which should be filled out with version and repro steps to allow for easier understanding what the issue might be. So next time use the template.

**Comment by hduongGW** [comment]
Could it be the description named RefinableString02 is also referred to as the HitHighlightedSummary property AND should be properly mapped/remapped to reflect this?  Is HitHighlightedSummary possible to be mapped?

**Comment by wobba** [comment]
Impossible to know as you are not sharing your setup for mp mapping or web part setup. But, seems like a data/mapping issue, not a web part issue per say.

**Comment by wobba** [comment]
This issue will shortly be closed due to inactivity.
